// Source-owned synthetic geometry. DOM/WebGL are inert: no GPU claim.
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const elements=new Map(),windowEvents=new Map();let uploads=[],pixelUploads=[],gpuCalls=[];function register(reg,type,handler){if(!reg.has(type))reg.set(type,[]);reg.get(type).push(handler);}function dispatch(el,type,event={}){for(const h of el.events?.get(type)||[])h(event);}function dispatchWindow(type,event={}){for(const h of windowEvents.get(type)||[])h(event);}
function element(id){if(!elements.has(id))elements.set(id,{id,value:id==='zonecolor'?'#aeb6bf':id==='zoneopacity'?'0.25':id==='markmode'?'inspect':id==='bin'?'64':id==='terrainoverlap'?'0.5':'200',checked:id==='terrain',tagName:'DIV',style:{},clientWidth:1000,clientHeight:700,width:1000,height:700,events:new Map(),addEventListener(type,handler){register(this.events,type,handler);},replaceChildren(){},append(){},focus(){context.document.activeElement=this;},blur(){if(context.document.activeElement===this)context.document.activeElement={tagName:"BODY"};},getBoundingClientRect(){return {left:0,top:0,width:1000,height:700};},getContext(){return new Proxy({},{get:(_,k)=>/^[A-Z_]+$/.test(k)?k:k==='texImage2D'?(...args)=>pixelUploads.push(Array.from(args[8])):k==='bufferData'?(target,data)=>uploads.push(data.length):k.startsWith('get')?()=>true:(...args)=>{gpuCalls.push([k,...args]);return {};}});}});return elements.get(id);}
const context=vm.createContext({console,DataView,TextDecoder,Uint8Array,Float32Array,Map,Set,Math,Array,Number,Error,JSON,Object,Infinity,performance:{now:()=>0},document:{addEventListener(){},getElementById:element,activeElement:{tagName:'BODY'},createElement:()=>element('option')},window:{addEventListener(type,handler){register(windowEvents,type,handler);}},requestAnimationFrame(){},setTimeout(){},URL:{},Blob:class{}});
const html=fs.readFileSync(process.argv[2]||require('path').join(__dirname,'..','tools','polycount_inspector.html'),'utf8');vm.runInContext(html.split(/<script>\s*/)[1].split('</script>')[0],context);
function scene(faces=[{x:0,z:5,model:1,range:10}],landName='g0'){
 let vertices=[[-10,-10,10],[10,-10,10],[10,10,10],[-10,10,10],[-10,-10,0],[10,-10,0],[10,10,0],[-10,10,0]];
 let polygons=[{vertices:[0,1,2,3],texinfo:0,texture:0,planeNormalZ:1},{vertices:[4,7,6,5],texinfo:0,texture:0,planeNormalZ:-1}];
 let objects=[{name:'Synthetic LAND',model:0,storedFaceRange:[0,2],reference:'land',faceCount:2,materialCount:1,vertices,polygons,edges:[[0,1],[1,2],[2,3],[3,0],[4,7],[7,6],[6,5],[5,4]],triangles:[[0,1,2],[0,2,3],[4,7,6],[4,6,5]]}];
 for(const f of faces){let p=[[-2+f.x,-2,f.z],[2+f.x,-2,f.z],[2+f.x,2,f.z],[-2+f.x,2,f.z]];objects.push({name:'Synthetic target',model:f.model,storedFaceRange:[f.range,1],reference:String(objects.length),faceCount:1,materialCount:1,vertices:p,edges:[[0,1],[1,2],[2,3],[3,0]],triangles:[[0,1,2],[0,2,3]],polygons:[{vertices:[0,1,2,3],texinfo:1,texture:1,planeNormalZ:1}]});}
 return {format:'amiwind-mesh-inspector-1',source:'synthetic-terrain.bsp',source_sha256:'a'.repeat(64),textures:[{name:landName,width:1,height:1,pixels:[80]},{name:'source_owned_checker',width:1,height:1,pixels:[200]}],objects};
}
function compute(s,overlap=.5){context.fixture=s;context.overlap=overlap;return JSON.parse(vm.runInContext('JSON.stringify(computeTerrainPreview(fixture,overlap))',context));}
let base=scene(),saved=JSON.stringify(base),r=compute(base);assert.equal(r.removedStored,1);assert.equal(r.removedPlaced,1);assert.equal(r.currentStored,2);assert.equal(r.bottom,0);assert.equal(r.groundTriangles,2);assert.equal(JSON.stringify(base),saved,'Calculation must not mutate original scene');
for(const z of [-1,0,.2,9.7,10,11])assert.equal(compute(scene([{x:0,z,model:1,range:10}])).removedStored,0,'Finite bottom/contact/above retained: '+z);
assert.equal(compute(scene([{x:20,z:5,model:1,range:10}])).removedStored,0,'Outside terrain retained');
let crossing=scene();crossing.objects[1].vertices[0][2]=12;assert.equal(compute(crossing).removedStored,0,'Crossing polygon remains complete');
for(const name of ['*water','sky0','stone0','g0water','g-1'])assert.equal(compute(scene(undefined,name)).removedStored,0,'Untrusted/non-LAND occluder rejected');
let water=scene();water.textures[1].name='*water';assert.equal(compute(water).removedStored,0,'Water target retained');
let gap=scene();gap.objects[0].vertices[2]=[10,-1,10];gap.objects[0].vertices[3]=[-10,-1,10];assert.equal(compute(gap).removedStored,0,'Partial terrain coverage cannot erase full face');
let shared=scene([{x:0,z:5,model:1,range:10},{x:0,z:12,model:2,range:10}]);r=compute(shared);assert.equal(r.stored,3);assert.equal(r.placed,4);assert.equal(r.removedStored,0,'Same stored face with exposed placement retained everywhere');
shared.objects[2].vertices.forEach(p=>p[2]=5);r=compute(shared);assert.equal(r.removedStored,1);assert.equal(r.removedPlaced,2,'Aliased model headers count shared removal once');
delete shared.objects[2].storedFaceRange;assert.equal(compute(shared).removedStored,0,'Missing alias metadata fails closed');
let noNormals=scene();delete noNormals.objects[0].polygons[0].planeNormalZ;assert.equal(compute(noNormals).removedStored,0,'No winding guess without original plane metadata');
assert.throws(()=>compute(scene(),-.1));assert.throws(()=>compute(scene(),Infinity));
let stilt=scene();stilt.objects[1].vertices=[[-2,0,5],[2,0,5],[2,0,15],[-2,0,15]];stilt.objects[1].polygons[0].lightmapped=false;stilt.objects[1].polygons[0].uv=[[0,0],[16,0],[16,16],[0,16]];
r=compute(stilt);assert.equal(r.clippedStored,1,'Unique unlightmapped crossing face clipped');assert.equal(r.removedStored,0,'Clipping one face does not invent a face-count reduction');assert(r.replacements[1][0].every(p=>p[2]>=9.5-1e-8));
context.fixture=stilt;vm.runInContext('load(fixture)',context);element('terraincull').checked=true;vm.runInContext('updateTerrainPreview()',context);
assert(vm.runInContext('shownPolygons(objects[1])[0].vertices.every(i=>shownVertices(objects[1])[i][2]>=9.5-1e-8)',context));
assert(vm.runInContext('shownPolygons(objects[1])[0].uv.every(p=>p[1]>=7.2-1e-7)',context),'Clipped UVs remain on original affine mapping');
assert.equal(vm.runInContext('scene.objects[1].vertices[0][2]',context),5,'Original crossing geometry retained in source scene');
stilt.objects[1].polygons[0].lightmapped=true;r=compute(stilt);assert.equal(r.clippedStored,0);assert.equal(r.sharedOrLightmappedRetained,1);
stilt.objects[1].polygons[0].lightmapped=false;stilt.objects.push(JSON.parse(JSON.stringify(stilt.objects[1])));stilt.objects[2].model=2;r=compute(stilt);assert.equal(r.clippedStored,0);assert.equal(r.sharedOrLightmappedRetained,1,'Shared crossing retained');
let fragmented=scene();fragmented.objects[1].vertices=[[-2,0,-5],[2,0,-5],[2,0,15],[-2,0,15]];fragmented.objects[1].polygons[0].lightmapped=false;r=compute(fragmented);assert.equal(r.clippedStored,0);assert.equal(r.fragmentGrowthRetained,1,'Two disconnected finite-depth remnants retained');
element('terraincull').checked=false;
context.fixture=scene();vm.runInContext('load(fixture)',context);element('terraincull').checked=true;vm.runInContext('updateTerrainPreview();render()',context);
assert.equal(vm.runInContext('shownPolygons(objects[1]).length',context),0);assert.equal(vm.runInContext('shownTriangles(objects[1]).length',context),0);assert.equal(vm.runInContext('shownEdges(objects[1]).length',context),0);assert.equal(vm.runInContext('objects[1].lineVertices',context),0);
assert.equal(vm.runInContext('scene.objects[1].polygons.length',context),1,'Scene export retains original face');assert.equal(vm.runInContext('scene.objects[1].triangles.length',context),2);
assert.match(element('previewcounts').textContent,/reduction 1 placed \/ 1 stored/);assert.equal(element('previewcounts').style.color,'#ff6b6b');assert.equal(element('terrainwarning').style.display,'block');
vm.runInContext('eye=[0,0,7];yaw=0;pitch=-Math.PI/2;pick(500,350)',context);assert.notEqual(vm.runInContext('selected',context),1,'Removed face cannot be picked');
element('terraincull').checked=false;vm.runInContext('updateTerrainPreview();render()',context);assert.equal(vm.runInContext('shownPolygons(objects[1]).length',context),1);assert.equal(vm.runInContext('objects[1].lineVertices',context),8);assert.equal(element('terrainwarning').style.display,'none');
vm.runInContext('eye=[0,0,7];yaw=0;pitch=-Math.PI/2;pick(500,350)',context);assert.equal(vm.runInContext('selected',context),1,'Original picking restored after OFF');
assert.equal(JSON.stringify(base),saved);assert.match(html,/requires pre-baking to affect the map/);
context.fixture=scene();vm.runInContext('load(fixture,"loaded-synthetic.json")',context);let identity=JSON.parse(vm.runInContext('JSON.stringify(polygonInfo())',context));assert.equal(identity.program.version,'0.0.28');assert.equal(identity.loaded_filename,'loaded-synthetic.json');assert.equal(identity.source_sha256,'a'.repeat(64));assert.equal(JSON.parse(vm.runInContext('JSON.stringify(exportSceneInfo())',context)).objects[1].faceCount,1);
console.log('PASS terrain preview: union coverage, finite depth, contact overlap, crossing/water/missing-data retention, shared storage, draw/pick OFF restoration, immutable original scene; DOM/WebGL stubs only.');
if(process.argv[3]){context.actual=JSON.parse(fs.readFileSync(process.argv[3],'utf8'));let start=Date.now();let actual=JSON.parse(vm.runInContext('globalThis.terrainResult=computeTerrainPreview(actual,.5);JSON.stringify(terrainResult)',context));delete actual.masks;delete actual.replacements;let before=JSON.stringify(context.actual);vm.runInContext('load(actual);document.getElementById("terraincull").checked=true;installTerrainPreview(terrainResult);rebuildLineBuffers();document.getElementById("textures").checked=true;render()',context);assert.equal(JSON.stringify(context.actual),before,'Actual scene remains immutable through clipping/draw preparation');const receipt={actual,elapsed_ms:Date.now()-start,clipped_geometry_and_UV_draw_preparation:true,original_scene_unchanged:true};if(process.argv[4])fs.writeFileSync(process.argv[4],JSON.stringify(receipt,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(receipt));}

// Append to the terrain-preview harness; all inputs here are synthetic.
context.fixture=scene();vm.runInContext('load(fixture,"synthetic-fixture.json")',context);
element('zoneminz').value='-2';element('zonemaxz').value='8';element('zonename').value='Test box';element('zoneopacity').value='0.35';element('zonezebra').checked=true;element('showzones').checked=true;
vm.runInContext('startZone("box");zoneCorners=[[1,2],[5,7]];finishZone()',context);
let zones=JSON.parse(vm.runInContext('JSON.stringify(zonesDocument())',context));assert.equal(zones.zones.length,1);assert.deepEqual(zones.zones[0].footprint_xy,[[1,2],[5,2],[5,7],[1,7]]);assert.equal(zones.zones[0].min_z,-2);assert.equal(zones.zones[0].max_z,8);assert.equal(zones.zones[0].style.opacity,.35);assert.equal(zones.zones[0].style.zebra,true);assert.equal(zones.program.version,'0.0.28');assert.equal(zones.loaded_filename,'synthetic-fixture.json');
element('zonename').value='Concave footprint';vm.runInContext('startZone("polygon");zoneCorners=[[0,0],[8,0],[8,8],[4,4],[0,8]];finishZone()',context);assert.equal(vm.runInContext('exclusionZones.length',context),2);
context.zoneData=JSON.parse(vm.runInContext('JSON.stringify(zonesDocument())',context));vm.runInContext('clearZones();applyInspectionImport(zoneData,"zones")',context);assert.equal(vm.runInContext('exclusionZones.length',context),2);assert.equal(JSON.parse(vm.runInContext('JSON.stringify(zonesDocument())',context)).zones[0].style.opacity,.35);
let malformed=JSON.parse(JSON.stringify(context.zoneData));malformed.zones[0].min_z=Infinity;context.bad=malformed;assert.throws(()=>vm.runInContext('applyInspectionImport(bad,"zones")',context));assert.equal(vm.runInContext('exclusionZones.length',context),2);
malformed=JSON.parse(JSON.stringify(context.zoneData));malformed.zones[0].footprint_xy=[[0,0],[4,4],[0,4],[4,0]];context.bad=malformed;assert.throws(()=>vm.runInContext('applyInspectionImport(bad,"zones")',context));
malformed=JSON.parse(JSON.stringify(context.zoneData));malformed.zones[1].id=malformed.zones[0].id;context.bad=malformed;assert.throws(()=>vm.runInContext('applyInspectionImport(bad,"zones")',context));
malformed=JSON.parse(JSON.stringify(context.zoneData));malformed.zones[0].style.opacity=1.5;context.bad=malformed;assert.throws(()=>vm.runInContext('applyInspectionImport(bad,"zones")',context));
vm.runInContext('eye=[1.123456789,2.987654321,30.2468];yaw=.71;pitch=-.45;focal=2.3;overhead=true;overheadScale=44;areaPoints=[[0,0,3],[4,0,3],[4,4,3]];areaPlane=3;areaClosed=true;select(1);selectZone(0)',context);
element('mode').value='density';element('textures').checked=true;element('heattextures').checked=false;element('overlay').checked=true;element('showcompass').checked=true;element('only').checked=true;element('filterdensity').checked=true;element('densitymin').value=0;element('densitymax').value=1;
let snapshot=JSON.parse(vm.runInContext('JSON.stringify(sessionDocument())',context));assert.equal(snapshot.program.version,'0.0.28');assert.equal(snapshot.loaded_filename,'synthetic-fixture.json');assert.equal(snapshot.source_sha256,'a'.repeat(64));assert.deepEqual(snapshot.camera.xyz,[1.123456789,2.987654321,30.2468]);assert.equal(snapshot.camera.projection,'orthographic');assert.equal(snapshot.zones.length,2);assert(!('objects' in snapshot));assert(!('textures' in snapshot));assert(!('palette' in snapshot));
context.snapshot=snapshot;let originalGeometry=JSON.stringify(context.fixture);vm.runInContext('eye=[999,999,999];exclusionZones=[];areaPoints=[];applyInspectionImport(snapshot,"session")',context);
let restored=JSON.parse(vm.runInContext('JSON.stringify(sessionDocument())',context));assert.deepEqual(restored.camera.xyz,snapshot.camera.xyz);assert.equal(restored.camera.focal,2.3);assert.equal(restored.camera.orthographic_scale,44);assert.deepEqual(restored.zones,snapshot.zones);assert.deepEqual(restored.polygon_area,snapshot.polygon_area);assert.equal(restored.display.mode,'density');assert.equal(restored.display.heattextures,false);assert.equal(restored.selection.reference,'1');assert.equal(JSON.stringify(context.fixture),originalGeometry);
let mismatch=JSON.parse(JSON.stringify(snapshot));mismatch.source_sha256='b'.repeat(64);mismatch.camera.xyz=[4,5,6];context.mismatch=mismatch;assert.equal(vm.runInContext('applyInspectionImport(mismatch,"session")',context),false);assert.deepEqual(JSON.parse(vm.runInContext('JSON.stringify(eye)',context)),snapshot.camera.xyz);assert.equal(element('applymismatch').style.display,'inline-block');assert.match(element('sessionstatus').textContent,/SHA-256 differs/);
assert.equal(vm.runInContext('applyInspectionImport(mismatch,"session",true)',context),true);assert.deepEqual(JSON.parse(vm.runInContext('JSON.stringify(eye)',context)),[4,5,6]);assert.match(element('sessionstatus').textContent,/explicit source-mismatch override/);
context.badSession={...snapshot,camera:{...snapshot.camera,xyz:[NaN,0,1]}};assert.throws(()=>vm.runInContext('applyInspectionImport(badSession,"session")',context));
assert.doesNotThrow(()=>vm.runInContext('drawZoneOverlays(document.getElementById("areaoverlay").getContext("2d"))',context));
vm.runInContext('deleteZone();clearZones()',context);assert.equal(vm.runInContext('exclusionZones.length',context),0);assert.equal(JSON.stringify(context.fixture),originalGeometry);
console.log('PASS planning/session: rectangular and concave polygon volumes, bounds/style validation, lossless coordinate/POV/style round-trip, source mismatch held until explicit override, original geometry unchanged; overlay GPU appearance untested.');

// Append to the synthetic inspector harness; no browser/GPU automation.
context.fixture=scene();vm.runInContext('load(fixture);select(1);eye=[0,-50,20];yaw=Math.PI/2;pitch=-.2;focal=1.8',context);
const originalEye=JSON.parse(vm.runInContext('JSON.stringify(eye)',context));vm.runInContext('enterOrbit()',context);assert.deepEqual(JSON.parse(vm.runInContext('JSON.stringify(orbitPivot)',context)),[0,0,5]);let radius=vm.runInContext('Math.hypot(...sub(eye,orbitPivot))',context);
for(const[axis,direction]of [['+X',[1,0,0]],['-X',[-1,0,0]],['+Y',[0,1,0]],['-Y',[0,-1,0]],['+Z',[0,0,1]],['-Z',[0,0,-1]]]){context.axis=axis;vm.runInContext('snapOrientation(axis)',context);let offset=JSON.parse(vm.runInContext('JSON.stringify(sub(eye,orbitPivot))',context));offset.forEach((v,i)=>assert(Math.abs(v-direction[i]*radius)<1e-8,axis+' camera side'));let forward=JSON.parse(vm.runInContext('JSON.stringify(basis().f)',context));forward.forEach((v,i)=>assert(Math.abs(v+direction[i])<1e-8,axis+' aims toward pivot'));assert.equal(vm.runInContext('orbitOrtho',context),true);}
vm.runInContext('orbitDrag(17,-8)',context);assert(Math.abs(vm.runInContext('Math.hypot(...sub(eye,orbitPivot))',context)-radius)<1e-8,'Orbit drag preserves radius');assert.equal(vm.runInContext('overhead',context),false);
element('showgizmo').checked=true;vm.runInContext('updateOrientationGizmo();updateButtonStates()',context);assert.equal(element('orientationgizmo').style.display,'block');assert.equal(element('vieworbit').ariaPressed,'true');assert.equal(element('returnfly').ariaPressed,'false');assert.equal(vm.runInContext('gizmoAxes.length',context),6);
context.orbitSession=JSON.parse(vm.runInContext('JSON.stringify(sessionDocument())',context));assert.equal(context.orbitSession.camera.orbit_enabled,true);assert.equal(context.orbitSession.camera.projection,'orthographic');assert.deepEqual(context.orbitSession.camera.orbit_pivot,[0,0,5]);assert.equal(context.orbitSession.display.showgizmo,true);
vm.runInContext('returnFly()',context);assert.deepEqual(JSON.parse(vm.runInContext('JSON.stringify(eye)',context)),originalEye);assert.equal(vm.runInContext('orbitMode',context),false);
vm.runInContext('applyInspectionImport(orbitSession,"session")',context);assert.equal(vm.runInContext('orbitMode',context),true);assert.deepEqual(JSON.parse(vm.runInContext('JSON.stringify(eye)',context)),context.orbitSession.camera.xyz);assert.deepEqual(JSON.parse(vm.runInContext('JSON.stringify(orbitPivot)',context)),context.orbitSession.camera.orbit_pivot);
vm.runInContext('inspectAbove();updateButtonStates()',context);assert.equal(vm.runInContext('overhead',context),true);assert.equal(vm.runInContext('orbitMode',context),false);assert.equal(vm.runInContext('pitch',context),-Math.PI/2);assert.equal(element('above').ariaPressed,'true');assert.equal(element('vieworbit').ariaPressed,'false');
vm.runInContext('areaPoints=[[0,0,0],[4,0,0],[4,4,0]];areaClosed=true;areaPlane=0;drawArea=true;zoneDrawing="polygon";zoneCorners=[[2,2]]',context);let stops=0,prevents=0;const event=(x,y)=>({clientX:x,clientY:y,pointerId:1,preventDefault(){prevents++;},stopPropagation(){stops++;}});context.e=event(5,5);vm.runInContext('gizmoPointerDown(e)',context);context.e=event(15,9);vm.runInContext('gizmoPointerMove(e);gizmoPointerUp(e)',context);assert.equal(stops,3);assert.equal(prevents,3);assert.equal(vm.runInContext('areaPoints.length',context),3,'Widget drag cannot add lasso corners');assert.equal(vm.runInContext('exclusionZones.length',context),0,'Widget drag cannot create zones');assert.equal(vm.runInContext('drawArea',context),false);
element('showgizmo').checked=false;vm.runInContext('updateOrientationGizmo()',context);assert.equal(element('orientationgizmo').style.display,'none');
console.log('PASS orientation gizmo: six cardinal snaps, true orthographic top, selected-object pivot, orbit radius, Fly restoration, source-bound session round-trip, pointer isolation; GPU appearance untested.');
// Source-owned palette and UI fixtures. Tests observe actual submitted RGBA bytes.
assert(!html.includes('id="textureColorMode"'),'No dropdown remains');
assert.match(html,/id="texturebw" aria-pressed="true">B\/W/);
assert.match(html,/id="texturecolor" aria-pressed="false">COLOR/);
assert.equal(vm.runInContext('textureColorMode()',context),'bw');
const builtin=Array.from(vm.runInContext('BUILTIN_PREVIEW_PALETTE',context));
assert.equal(builtin.length,768);assert(builtin.every(n=>Number.isInteger(n)&&n>=0&&n<=255));
assert.deepEqual(builtin.slice(600,603),[255,153,102]);
for(let i=0;i<40;i++)assert.deepEqual(builtin.slice((216+i)*3,(217+i)*3),Array(3).fill(Math.round(i*255/39)));
context.fixture=scene();const baseBefore=JSON.stringify(context.fixture);vm.runInContext('load(fixture)',context);
element('textures').checked=false;element('textures').onchange();assert.equal(element('texturecolorchoice').style.display,'none');
assert.equal(element('texturebw').ariaPressed,'true');assert.equal(element('texturecolor').ariaPressed,'false');assert.equal(element('palettebuiltin').ariaPressed,'true');
element('textures').checked=true;element('textures').onchange();assert.equal(element('texturecolorchoice').style.display,'block');
element('texturecolor').onclick();assert.equal(element('texturecolor').ariaPressed,'true');assert.equal(element('texturebw').ariaPressed,'false');
pixelUploads=[];vm.runInContext('prepareSolids()',context);assert.deepEqual(pixelUploads[1],[255,153,102,255],'COLOR available immediately from built-in palette');
assert.match(element('texturestatus').textContent,/Built-in preview palette/);assert.match(element('texturestatus').textContent,/not original game colors/);
element('texturebw').onclick();assert.equal(vm.runInContext('solidReady',context),false);pixelUploads=[];vm.runInContext('prepareSolids()',context);let gray=Math.round(.299*255+.587*153+.114*102);assert.deepEqual(pixelUploads[1],[gray,gray,gray,255]);
assert.equal(JSON.stringify(context.fixture),baseBefore,'Built-in palette is not inserted into source scene');
context.fixture=scene();context.fixture.palette=Array(768).fill(0);context.fixture.palette.splice(600,3,20,160,240);
const localBefore=JSON.stringify(context.fixture);vm.runInContext('load(fixture);loadedPaletteFilename="source-owned-test.lmp"',context);
assert.equal(vm.runInContext('textureColorMode()',context),'bw','Loading palette keeps B/W mode');
element('texturecolor').onclick();pixelUploads=[];vm.runInContext('prepareSolids()',context);assert.deepEqual(pixelUploads[1],[20,160,240,255]);assert.equal(element('palettelocal').ariaPressed,'true');
element('palettebuiltin').onclick();pixelUploads=[];vm.runInContext('prepareSolids()',context);assert.deepEqual(pixelUploads[1],[255,153,102,255]);
element('palettelocal').onclick();element('texturebw').onclick();pixelUploads=[];vm.runInContext('prepareSolids()',context);gray=Math.round(.299*20+.587*160+.114*240);assert.deepEqual(pixelUploads[1],[gray,gray,gray,255]);assert.equal(JSON.stringify(context.fixture),localBefore,'Palette choices preserve original local bytes');
element('texturecolor').onclick();element('textures').checked=false;element('textures').onchange();
context.localSession=JSON.parse(vm.runInContext('JSON.stringify(sessionDocument())',context));assert.equal(context.localSession.display.textureColorMode,'color');assert.equal(context.localSession.display.textures,false);assert.equal(context.localSession.palette_reference.kind,'local');assert.equal(context.localSession.palette_reference.filename,'source-owned-test.lmp');assert.equal(context.localSession.program.version,'0.0.28');
element('palettebuiltin').onclick();element('texturebw').onclick();vm.runInContext('applyInspectionImport(localSession,"session")',context);assert.equal(element('texturecolor').ariaPressed,'true');assert.equal(element('palettelocal').ariaPressed,'true');assert.equal(element('texturecolorchoice').style.display,'none');assert.equal(vm.runInContext('localPaletteReady()',context),true);
context.noPalette=scene();vm.runInContext('load(noPalette);applyInspectionImport(localSession,"session")',context);assert.equal(vm.runInContext('localPaletteReady()',context),false);assert.equal(vm.runInContext('loadedPaletteFilename',context),null,'Import never invents a loaded local filename');assert.equal(vm.runInContext('paletteReference().filename',context),'source-owned-test.lmp');assert.match(element('texturestatus').textContent,/Requested local palette is missing/);assert.match(element('texturestatus').textContent,/Built-in preview palette/);
pixelUploads=[];vm.runInContext('prepareSolids()',context);assert.deepEqual(pixelUploads[1],[255,153,102,255],'Missing referenced local palette uses explicit built-in preview');
element('palettebuiltin').onclick();context.builtinSession=JSON.parse(vm.runInContext('JSON.stringify(sessionDocument())',context));assert.equal(context.builtinSession.palette_reference.kind,'builtin');assert.equal(context.builtinSession.palette_reference.builtin_id,'amiwind-rgb216-gray40-v1');
element('palettelocal').onclick();vm.runInContext('applyInspectionImport(builtinSession,"session")',context);assert.equal(element('palettebuiltin').ariaPressed,'true');assert(!element('texturestatus').textContent.includes('Requested local palette is missing'));
context.invalid=JSON.parse(JSON.stringify(context.builtinSession));context.invalid.palette_reference.kind='unknown';assert.throws(()=>vm.runInContext('applyInspectionImport(invalid,"session")',context));
context.legacy=JSON.parse(JSON.stringify(context.builtinSession));delete context.legacy.display.textureColorMode;delete context.legacy.palette_reference.kind;delete context.legacy.palette_reference.builtin_id;vm.runInContext('applyInspectionImport(legacy,"session")',context);assert.equal(vm.runInContext('textureColorMode()',context),'bw');
element('textures').checked=true;vm.runInContext('inspectAbove();render()',context);assert.equal(element('texturecolorchoice').style.display,'none');vm.runInContext('returnFly();render()',context);assert.equal(element('texturecolorchoice').style.display,'block');
console.log('PASS texture buttons/palettes: B/W default, active highlights/visibility,256 original RGB entries and gray ramp, exact built-in/local uploads, retained palette, hidden-mode/source-bound session and explicit missing-local restoration.');

// Deterministic clock/zone fixture; production uses the browser's actual current time.
const realDate=context.Date,realIntl=context.Intl;
context.Date=class extends Date{
 constructor(...args){super(...(args.length?args:['2026-10-03T20:15:30.123Z']));}
 getTimezoneOffset(){return -180;}
 getFullYear(){return new Date(this.getTime()+10800000).getUTCFullYear();}
 getMonth(){return new Date(this.getTime()+10800000).getUTCMonth();}
 getDate(){return new Date(this.getTime()+10800000).getUTCDate();}
 getHours(){return new Date(this.getTime()+10800000).getUTCHours();}
 getMinutes(){return this.getUTCMinutes();}getSeconds(){return this.getUTCSeconds();}getMilliseconds(){return this.getUTCMilliseconds();}
};
context.Intl={DateTimeFormat:()=>({resolvedOptions:()=>({timeZone:'Europe/Helsinki'})})};
context.clockFixture=scene();context.clockFixture.source='sn045.bsp';vm.runInContext('load(clockFixture,"loaded-candidate-sn045.bsp")',context);
const timed=JSON.parse(vm.runInContext('JSON.stringify(sessionDocument())',context));
assert.equal(timed.exported_at_utc,'2026-10-03T20:15:30.123Z');assert.equal(timed.exported_at_local,'2026-10-03T23:15:30.123+03:00');assert.equal(timed.exported_at_timezone,'Europe/Helsinki');
assert.equal(timed.source_filename,'sn045.bsp');assert.equal(timed.loaded_filename,'loaded-candidate-sn045.bsp');assert.equal(timed.source_sha256,'a'.repeat(64));
context.timed=timed;assert.equal(vm.runInContext('inspectionExportFilename("inspection-session",timed)',context),'PRIVATE-inspection-session-sn045-20261003T231530+0300.json');
const capture=[];context.downloadBlob=(blob,name)=>capture.push(name);
element('exportall').onclick();element('zoneexport').onclick();vm.runInContext('areaPoints=[[0,0,0],[1,0,0],[1,1,0]]',context);element('areaJSON').onclick();element('export').onclick();
for(const name of capture){assert(name.includes('-sn045-20261003T231530+0300.json'));assert(!/[<>:"/\\|?*\x00-\x1f]/.test(name));}
assert.equal(capture.length,4);assert(capture[0].startsWith('PRIVATE-inspection-session-'));assert(capture[1].startsWith('PRIVATE-exterior-prebake-exclusions-'));
context.odd={...timed,source_filename:'C:\\private\\sn045:trial?roof*.bsp'};const safe=vm.runInContext('inspectionExportFilename("inspection-session",odd)',context);assert.equal(safe,'PRIVATE-inspection-session-sn045-trial-roof-20261003T231530+0300.json');
context.west={...timed,exported_at_local:'2026-01-02T03:04:05.006-05:30'};assert.equal(vm.runInContext('inspectionExportFilename("inspection-session",west)',context),'PRIVATE-inspection-session-sn045-20260102T030405-0530.json');
for(const expression of ['polygonInfo()','zonesDocument()','exportSceneInfo()']){const d=JSON.parse(vm.runInContext('JSON.stringify('+expression+')',context));assert.equal(d.exported_at_utc,timed.exported_at_utc);assert.equal(d.source_sha256,timed.source_sha256);}
if(realDate===undefined)delete context.Date;else context.Date=realDate;if(realIntl===undefined)delete context.Intl;else context.Intl=realIntl;
console.log('PASS export identity/time: actual-clock API, deterministic UTC/local/zone receipt, map/source hash retained, session/zones/polygon/scene filenames, Windows-safe sanitization and westward timezone offset.');
// Source-owned viewport focus, browser-shortcut ownership and wall-clock movement checks.
context.navigationFixture=scene();vm.runInContext('load(navigationFixture);eye=[0,0,0];yaw=0;pitch=0;overhead=false;orbitMode=false',context);
element('view').tagName='CANVAS';element('copysessiontext').tagName='TEXTAREA';element('speed').value=100;
function keyEvent(key,opts={}){return {key,target:context.document.activeElement,shiftKey:false,ctrlKey:false,altKey:false,metaKey:false,prevented:false,preventDefault(){this.prevented=true;},...opts};}
for(const editable of [{tagName:'INPUT'},{tagName:'SELECT'},element('copysessiontext'),{tagName:'DIV',isContentEditable:true},{tagName:'SPAN',closest:()=>({isContentEditable:true})}]){
 context.document.activeElement=editable;context.keyEvent=keyEvent('a',{ctrlKey:true});vm.runInContext('keys.add("w");navigationKeyDown(keyEvent);last=0;tick(100)',context);assert.equal(context.keyEvent.prevented,false,'Text editing keeps Ctrl+A');assert.equal(vm.runInContext('keys.size',context),0);assert.deepEqual(JSON.parse(vm.runInContext('JSON.stringify(eye)',context)),[0,0,0]);
}
context.document.activeElement=element('copysessiontext');vm.runInContext('keys.add("w");returnFly()',context);assert.strictEqual(context.document.activeElement,element('view'));assert.equal(vm.runInContext('keys.size',context),0,'Fly clears stale held keys');
context.document.activeElement=element('copysessiontext');let pointerRequests=0;element('view').requestPointerLock=()=>pointerRequests++;element('fly').onclick();assert.strictEqual(context.document.activeElement,element('view'));assert.equal(pointerRequests,1,'Enter mouse look focuses viewport before lock');
for(const key of ['w','a','s','d']){context.keyEvent=keyEvent(key,{ctrlKey:true});vm.runInContext('navigationKeyDown(keyEvent)',context);assert.equal(context.keyEvent.prevented,true,'Viewport consumes Ctrl+'+key);assert.equal(vm.runInContext('keys.has("control")',context),true);}
context.keyEvent=keyEvent('w',{ctrlKey:true,shiftKey:true});vm.runInContext('navigationKeyDown(keyEvent)',context);assert.equal(vm.runInContext('keys.has("shift")&&keys.has("control")',context),true,'Modifiers come from movement event flags');
context.keyEvent=keyEvent('w');vm.runInContext('navigationKeyUp(keyEvent)',context);assert.equal(vm.runInContext('keys.has("control")||keys.has("shift")||keys.has("w")',context),false);
context.document.activeElement={tagName:'BODY'};context.keyEvent=keyEvent('w',{ctrlKey:true});vm.runInContext('navigationKeyDown(keyEvent)',context);assert.equal(context.keyEvent.prevented,false,'Browser shortcuts outside viewport untouched');
context.document.activeElement=element('view');
for(const fps of [60,20,10,5,2])for(const [shift,ctrl,multiplier] of [[false,false,1],[true,false,2],[false,true,4],[true,true,8]]){
 vm.runInContext('keys.clear();eye=[0,0,0];yaw=0;pitch=0;overhead=false;orbitMode=false;last=0',context);context.keyEvent=keyEvent('w',{shiftKey:shift,ctrlKey:ctrl});vm.runInContext('navigationKeyDown(keyEvent)',context);
 for(let i=1;i<=fps;i++){context.time=i*1000/fps;vm.runInContext('tick(time)',context);}
 let distance=vm.runInContext('eye[0]',context);assert(Math.abs(distance-100*multiplier)<1e-7,`${fps}FPS modifier${multiplier}: ${distance}`);
}
vm.runInContext('eye=[0,0,0];last=0;tick(1000)',context);assert.equal(vm.runInContext('eye[0]',context),0,'Long suspension does not jump the camera');
context.document.hidden=true;vm.runInContext('last=1000;tick(1100)',context);assert.equal(vm.runInContext('eye[0]',context),0,'Hidden document cannot fly');context.document.hidden=false;
vm.runInContext('keys.add("w");resetNavigation()',context);assert.equal(vm.runInContext('keys.size',context),0);
vm.runInContext('globalThis.originalFaceTotals=previewFaceTotals;globalThis.totalCalls=0;previewFaceTotals=(...args)=>{totalCalls++;return originalFaceTotals(...args);}',context);
element('terraincull').checked=false;vm.runInContext('load(navigationFixture)',context);const calls=vm.runInContext('totalCalls',context);assert.equal(calls,1,'One baseline traversal at source load');
vm.runInContext('for(let i=0;i<100;i++)terrainPreviewStatus()',context);assert.equal(vm.runInContext('totalCalls',context),calls,'OFF status never traverses faces per rendered frame');
vm.runInContext('load(navigationFixture)',context);assert.equal(vm.runInContext('totalCalls',context),calls+1,'Loading another scene refreshes totals');vm.runInContext('previewFaceTotals=originalFaceTotals',context);
console.log('PASS flight repair: textarea/contenteditable shortcut safety; Fly viewport focus; Ctrl+WASD capture scoped to viewport; event modifier recovery; equal2/5/10/20/60FPS movement at1/2/4/8x; stall/hidden reset; cached static face counts.');

// Clipboard success/failure are mocked; no host clipboard is read or written.
// Bounded exterior markup fixture: two placements share a model but remain independently marked.
context.fixture=scene([{x:0,z:5,model:1,range:10},{x:20,z:5,model:1,range:10}]);const markupGeometry=JSON.stringify(context.fixture);
element('zonecolor').value='#cc2244';element('zoneopacity').value='.4';element('zonezebra').checked=true;
vm.runInContext('load(fixture,"source-owned-interior-example.bsp");const strokeBefore=markupSnapshot();markFace(1,0);markFace(2,0);commitMarkup(strokeBefore)',context);
assert.equal(vm.runInContext('faceMarks.length',context),2);assert.equal(vm.runInContext('markupUndo.length',context),1,'One stroke is one undo level');
vm.runInContext('undoMarkup()',context);assert.equal(vm.runInContext('faceMarks.length',context),0);vm.runInContext('redoMarkup()',context);assert.equal(vm.runInContext('faceMarks.length',context),2);
vm.runInContext('const eraseBefore=markupSnapshot();markFace(1,0,true);commitMarkup(eraseBefore)',context);assert.equal(vm.runInContext('faceMarks.length',context),1);assert.equal(vm.runInContext('faceMarks[0].object_index',context),2,'Shared model marks remain placement specific');vm.runInContext('undoMarkup()',context);
element('zoneminz').value='0';element('zonemaxz').value='8';element('zonename').value='Synthetic closed interior';vm.runInContext('startZone("box");zoneCorners=[[-3,-3],[3,3]];finishZone()',context);
context.markup=JSON.parse(vm.runInContext('JSON.stringify(zonesDocument())',context));assert.equal(context.markup.face_marks[0].stored_face_id,10);assert.equal(context.markup.face_marks[0].scope,'this_placement');assert.equal(context.markup.exterior_prebake_exclusion.collision,'preserve_unchanged');assert.equal(context.markup.exterior_prebake_exclusion.status,'markup_only');assert.equal(context.markup.source_sha256,'a'.repeat(64));assert.equal(context.markup.program.version,'0.0.28');assert(context.markup.exported_at_utc||context.markup.exported_utc||context.markup.created_at_utc||JSON.stringify(context.markup).includes('UTC'));
const box=context.markup.zones[0],inside=p=>p[0]>=-3&&p[0]<=3&&p[1]>=-3&&p[1]<=3&&p[2]>=box.min_z&&p[2]<=box.max_z;
assert(context.markup.face_marks[0].points_xyz.every(inside));assert(!context.markup.face_marks[1].points_xyz.some(inside),'Second placement outside simple volume');
vm.runInContext('faceMarks=[];exclusionZones=[];applyInspectionImport(markup,"zones")',context);assert.equal(vm.runInContext('faceMarks.length',context),2);assert.equal(vm.runInContext('exclusionZones.length',context),1);vm.runInContext('undoMarkup()',context);assert.equal(vm.runInContext('faceMarks.length',context),0);vm.runInContext('redoMarkup()',context);assert.equal(vm.runInContext('faceMarks.length',context),2);
element('zonecolor').value='#1166ee';element('zonecolor').onchange();assert.equal(vm.runInContext('faceMarks.every(m=>m.style.color==="#1166ee")&&exclusionZones.every(z=>z.style.color==="#1166ee")',context),true);vm.runInContext('undoMarkup()',context);assert.equal(vm.runInContext('faceMarks[0].style.color',context),'#cc2244');
context.invalid=JSON.parse(JSON.stringify(context.markup));context.invalid.face_marks[0].points_xyz[0][0]+=1;assert.throws(()=>vm.runInContext('applyInspectionImport(invalid,"zones")',context),/binding or geometry/);
context.invalid=JSON.parse(JSON.stringify(context.markup));context.invalid.zones[0].style.color='url(javascript:x)';assert.throws(()=>vm.runInContext('applyInspectionImport(invalid,"zones")',context),/#RRGGBB/);
context.invalid=JSON.parse(JSON.stringify(context.markup));context.invalid.exterior_prebake_exclusion.collision='remove';assert.throws(()=>vm.runInContext('applyInspectionImport(invalid,"zones")',context),/Unsupported/);
context.legacy=JSON.parse(JSON.stringify(context.markup));delete context.legacy.face_marks;delete context.legacy.face_mark_schema;delete context.legacy.exterior_prebake_exclusion;delete context.legacy.zone_display;delete context.legacy.zones[0].style.color;vm.runInContext('applyInspectionImport(legacy,"zones")',context);assert.equal(vm.runInContext('faceMarks.length',context),0);assert.equal(vm.runInContext('exclusionZones[0].style.color',context),'#aeb6bf');
assert.equal(JSON.stringify(context.fixture),markupGeometry,'Markup never modifies geometry/collision');
if(process.env.AW_MARKUP_FIXTURE)fs.writeFileSync(process.env.AW_MARKUP_FIXTURE,JSON.stringify(context.markup,null,2)+'\n');
console.log('PASS exterior markup: inside/outside source-owned fixture, exact placement face IDs, grouped paint/erase undo/redo, volume/history import/reapply, global RGB, invalid color/binding/intent rejection, legacy gray import, source hash/version/time, immutable geometry; compiler consumption and GPU appearance untested.');



context.rayFixture=scene();for(let i=0;i<4;i++)context.rayFixture.objects[0].vertices[i][2]=0;
element('only').checked=false;element('filterdensity').checked=false;element('terraincull').checked=false;
vm.runInContext('load(rayFixture);eye=[0,0,30];yaw=0;pitch=-Math.PI/2;overhead=true',context);
assert.deepEqual(JSON.parse(vm.runInContext('JSON.stringify(hitExactFace(500,350))',context)),[1,0,0,'front'],'Crosshair picks nearest exact face, not texture or full model');
let preventedUndo=0;context.undoEvent={key:'z',ctrlKey:true,shiftKey:false,target:{tagName:'TEXTAREA'},preventDefault:()=>preventedUndo++};context.document.activeElement={tagName:'TEXTAREA'};vm.runInContext('navigationKeyDown(undoEvent)',context);assert.equal(preventedUndo,0,'Text input retains Ctrl+Z');
console.log('PASS exact crosshair ray target and text-input Ctrl+Z isolation.');

// Regression014: use the actual buttons and registered pointer handlers, not only helper calls.
context.realMap=scene();context.realMap.palette=Array(768).fill(90);vm.runInContext('load(realMap,"real-map-test.bsp");eye=[4,-25,15];loadedPaletteFilename="local-test.lmp";selectedPaletteKind="local";const initialMark=markupSnapshot();markFace(1,0);commitMarkup(initialMark)',context);
const beforeDemo=JSON.parse(vm.runInContext('JSON.stringify({session:sessionDocument(),undo:markupUndo,redo:markupRedo,palette:loadedPaletteFilename,source:scene})',context));
element('demo').onclick();assert.equal(element('demo').textContent,'Return to map');assert.equal(vm.runInContext('objects[0].polygons.length',context),6,'Actual cube builder exposes six polygons');
element('zonecolor').value='#000000';element('zoneopacity').value='1';element('zonezebra').checked=false;element('painttoggle').onclick();assert.equal(element('painttoggle').ariaPressed,'true');assert.match(element('painttoggle').textContent,/ON/);
vm.runInContext('eye=[0,-30,0];yaw=Math.PI/2;pitch=0;overhead=false;document.pointerLockElement=canvas',context);
const pointer={clientX:100,clientY:100,movementX:0,movementY:0};dispatch(element('view'),'pointerdown',pointer);dispatch(element('view'),'mousemove',pointer);dispatchWindow('pointerup');dispatch(element('view'),'click',pointer);
// Canvas has its real ID, detect it from the captured navigation element if renamed.
assert.equal(vm.runInContext('faceMarks.length',context),1,'Actual cube pointer click paints');assert.equal(vm.runInContext('faceMarks[0].points_xyz.length',context),3,'Click marks one triangle, not whole polygon');assert.equal(vm.runInContext('markupUndo.length',context),1,'One drag/click yields one undo entry');
element('markupundo').onclick();assert.equal(vm.runInContext('faceMarks.length',context),0);element('markupredo').onclick();assert.equal(vm.runInContext('faceMarks.length',context),1);
element('markerase').onclick();dispatch(element('view'),'pointerdown',pointer);dispatchWindow('pointerup');assert.equal(vm.runInContext('faceMarks.length',context),0);element('markupundo').onclick();assert.equal(vm.runInContext('faceMarks.length',context),1);
context.cubeMarks=JSON.parse(vm.runInContext('JSON.stringify(zonesDocument())',context));vm.runInContext('faceMarks=[];applyInspectionImport(cubeMarks,"zones")',context);assert.equal(vm.runInContext('faceMarks[0].triangle_index',context),0);vm.runInContext('const otherTriangle=markupSnapshot();markFace(0,faceMarks[0].face_index,false,1);commitMarkup(otherTriangle)',context);assert.equal(vm.runInContext('faceMarks.length',context),2,'Two triangles of one polygon remain distinct');
vm.runInContext('document.pointerLockElement=null',context);element('demo').onclick();assert.equal(element('demo').textContent,'Synthetic cube');const afterDemo=JSON.parse(vm.runInContext('JSON.stringify({session:sessionDocument(),undo:markupUndo,redo:markupRedo,palette:loadedPaletteFilename,source:scene})',context));delete beforeDemo.session.exported_at_utc;delete beforeDemo.session.exported_at_local;delete afterDemo.session.exported_at_utc;delete afterDemo.session.exported_at_local;assert.deepEqual(afterDemo,beforeDemo,'Demo return preserves map, camera, masks, history and palette');
// A room wall crosses the eye near plane but still has a valid center triangle hit.
context.room={format:'amiwind-mesh-inspector-1',source:'source-owned-room.json',source_sha256:'b'.repeat(64),objects:[{name:'Room wall',model:1,reference:'room',faceCount:1,materialCount:1,vertices:[[-1,-2,-2],[3,2,-2],[3,2,2],[-1,-2,2]],edges:[[0,1],[1,2],[2,3],[3,0]],triangles:[[0,1,2],[0,2,3]],polygons:[{vertices:[0,1,2,3],texinfo:0}]}]};
vm.runInContext('load(room);eye=[0,0,0];yaw=0;pitch=0;overhead=false;document.pointerLockElement=canvas',context);element('painttoggle').onclick();dispatch(element('view'),'pointerdown',pointer);dispatchWindow('pointerup');assert.equal(vm.runInContext('faceMarks.length',context),1);assert(vm.runInContext('projectOverlayPolygon(faceMarks[0].points_xyz).length',context)>=3,'Near-plane crossing mark remains projected');
gpuCalls=[];element('showzones').checked=true;vm.runInContext('drawFaceMarks()',context);assert(gpuCalls.some(c=>c[0]==='drawArrays'&&c[3]===3),'Actual GPU paint draws crossing triangle');assert(gpuCalls.some(c=>c[0]==='enable'&&c[1]==='DEPTH_TEST'),'Paint depth test enabled');assert(gpuCalls.some(c=>c[0]==='colorMask'&&c.slice(1).every(x=>x===false)),'Opaque depth-only prepass');
vm.runInContext('scene=null;objects=[];demoReturn=null;demoActive=false;document.pointerLockElement=null',context);element('demo').onclick();assert.equal(element('demo').textContent,'Close synthetic cube');element('demo').onclick();assert.equal(vm.runInContext('scene===null&&objects.length===0',context),true,'Demo can turn off without previous map');
console.log('PASS014 registered controls: actual demo triangles, header ON/OFF, pointer-locked click/drag paint, triangle-only export/reload, erase and undo/redo; reversible demo preserves map/camera/masks/history/palette; near-plane room triangle submits GPU paint with depth prepass; empty demo closes. GPU appearance untested.');

// Regression015: nearest visible surface and independently annotated sides.
context.overlap={format:'amiwind-mesh-inspector-1',source:'source-owned-overlap.json',source_sha256:'c'.repeat(64),objects:[{name:'Overlapping panels',model:1,reference:'panels',faceCount:2,materialCount:1,vertices:[[2,-2,-2],[2,2,-2],[2,0,2],[4,-2,-2],[4,2,-2],[4,0,2]],edges:[[0,1],[1,2],[2,0],[3,4],[4,5],[5,3]],triangles:[[0,1,2],[3,4,5]],polygons:[{vertices:[0,1,2],texinfo:0},{vertices:[3,4,5],texinfo:0}]}]};
vm.runInContext('load(overlap);eye=[0,0,0];yaw=0;pitch=0;overhead=false;document.pointerLockElement=canvas',context);element('painttoggle').onclick();dispatch(element('view'),'pointerdown',pointer);dispatchWindow('pointerup');
assert.equal(vm.runInContext('faceMarks.length',context),1);assert.equal(vm.runInContext('faceMarks[0].face_index',context),0,'First panel stops paint ray');assert.equal(vm.runInContext('faceMarks[0].clicked_side',context),'back');assert.equal(vm.runInContext('faceMarks[0].cut_scope',context),'clicked_render_side_only');assert.equal(vm.runInContext('markSideVisible(faceMarks[0])',context),true);
vm.runInContext('eye=[3,0,0];yaw=Math.PI;pitch=0',context);assert.equal(vm.runInContext('markSideVisible(faceMarks[0])',context),false,'Same triangle reverse side never shows original mark');dispatch(element('view'),'pointerdown',pointer);dispatchWindow('pointerup');assert.equal(vm.runInContext('faceMarks.length',context),2,'Opposite side has independent key');assert.equal(vm.runInContext('faceMarks[1].clicked_side',context),'front');assert.equal(vm.runInContext('faceMarks[1].points_xyz.length',context),3);
element('markerase').onclick();dispatch(element('view'),'pointerdown',pointer);dispatchWindow('pointerup');assert.equal(vm.runInContext('faceMarks.length',context),1,'Erase affects clicked side only');assert.equal(vm.runInContext('faceMarks[0].clicked_side',context),'back');element('markupundo').onclick();assert.equal(vm.runInContext('faceMarks.length',context),2);
context.sidePlan=JSON.parse(vm.runInContext('JSON.stringify(zonesDocument())',context));vm.runInContext('faceMarks=[];applyInspectionImport(sidePlan,"zones")',context);assert.equal(vm.runInContext('faceMarks[1].cut_scope',context),'clicked_render_side_only');
for(const textured of [false,true]){element('textures').checked=textured;gpuCalls=[];vm.runInContext('drawFaceMarks()',context);assert(gpuCalls.some(c=>c[0]==='enable'&&c[1]==='DEPTH_TEST'));assert(gpuCalls.some(c=>c[0]==='depthFunc'&&c[1]==='LEQUAL'));assert(gpuCalls.some(c=>c[0]==='depthMask'&&c[1]===false));assert(!gpuCalls.some(c=>c[0]==='polygonOffset'),'No bias can jump across a nearby wall');assert.equal(gpuCalls.filter(c=>c[0]==='drawArrays').length,2,'Depth pass and only current side paint pass');}
for(const textured of [false,true]){element('textures').checked=textured;gpuCalls=[];vm.runInContext('render()',context);const draws=gpuCalls.filter(c=>c[0]==='drawArrays');assert(draws.slice(-2).every(c=>c[1]==='TRIANGLES'),'Actual renderer ends in source depth and side-gated paint passes');assert(gpuCalls.some(c=>c[0]==='depthMask'&&c[1]===false));}
context.oldPlan=JSON.parse(JSON.stringify(context.sidePlan));context.oldPlan.face_marks=context.oldPlan.face_marks.slice(0,1);delete context.oldPlan.face_marks[0].clicked_side;delete context.oldPlan.face_marks[0].cut_scope;vm.runInContext('applyInspectionImport(oldPlan,"zones")',context);assert.equal(vm.runInContext('faceMarks[0].clicked_side',context),'unspecified');assert.equal(vm.runInContext('faceMarks[0].cut_scope',context),'legacy_unspecified_side_review_required');
assert(!html.includes('drawFaceMarks(c);'),'Paint is no longer a 2D planning overlay');
console.log('PASS015 side/depth: nearest overlapping panel, reverse side suppressed, opposite-side independent paint/erase/undo, explicit side-only JSON reload, legacy review flag, texture ON/OFF depth-only prepass and LEQUAL pass with zero offset; GPU pixel appearance unverified.');

// Regression016: Draw box keeps the current interior fly POV and samples visible surfaces.
context.floorRoom={format:'amiwind-mesh-inspector-1',source:'source-owned-floor-room.json',source_sha256:'d'.repeat(64),objects:[{name:'Room floor',model:1,reference:'room-floor',faceCount:1,materialCount:1,vertices:[[-30,-30,0],[30,-30,0],[30,30,0],[-30,30,0]],edges:[[0,1],[1,2],[2,3],[3,0]],triangles:[[0,1,2],[0,2,3]],polygons:[{vertices:[0,1,2,3],texinfo:0}]}]};
vm.runInContext('load(floorRoom);eye=[0,-10,10];yaw=Math.PI/2;pitch=-Math.PI/4;overhead=false;orbitMode=false;document.pointerLockElement=null;moved=0',context);element('mode').value='white';element('textures').checked=true;element('zoneminz').value='-1';element('zonemaxz').value='9';
const boxView=vm.runInContext('JSON.stringify({eye,yaw,pitch,overhead,orbitMode,focal,mode:$("mode").value,textures:$("textures").checked})',context);element('zonebox').onclick();assert.equal(vm.runInContext('JSON.stringify({eye,yaw,pitch,overhead,orbitMode,focal,mode:$("mode").value,textures:$("textures").checked})',context),boxView,'Draw box must never jump overhead');
const cornerA={clientX:400,clientY:300,movementX:0,movementY:0},cornerB={clientX:600,clientY:400,movementX:0,movementY:0};for(const e of [cornerA,cornerB]){dispatch(element('view'),'pointerdown',e);dispatchWindow('pointerup');dispatch(element('view'),'click',e);if(e===cornerA){assert.equal(vm.runInContext('zoneCorners.length',context),1);dispatch(element('view'),'mousemove',cornerB);assert.equal(vm.runInContext('zoneHoverWorld!==null',context),true,'Ghost box follows a surface hit');}}
assert.equal(vm.runInContext('exclusionZones.length',context),1);assert.equal(vm.runInContext('exclusionZones[0].min_z',context),-1);assert.equal(vm.runInContext('exclusionZones[0].max_z',context),9);assert.equal(vm.runInContext('JSON.stringify({eye,yaw,pitch,overhead,orbitMode,focal,mode:$("mode").value,textures:$("textures").checked})',context),boxView,'Clicks preserve fly POV');
context.flyBoxPlan=JSON.parse(vm.runInContext('JSON.stringify(zonesDocument())',context));assert(context.flyBoxPlan.zones[0].footprint_xy.every(p=>p.every(Number.isFinite)));assert.equal(context.flyBoxPlan.source_sha256,'d'.repeat(64));element('markupundo').onclick();assert.equal(vm.runInContext('exclusionZones.length',context),0);element('markupredo').onclick();assert.equal(vm.runInContext('exclusionZones.length',context),1);vm.runInContext('exclusionZones=[];applyInspectionImport(flyBoxPlan,"zones")',context);assert.deepEqual(JSON.parse(vm.runInContext('JSON.stringify(exclusionZones[0].footprint_xy)',context)),context.flyBoxPlan.zones[0].footprint_xy);
vm.runInContext('pitch=Math.PI/4;moved=0',context);element('zonebox').onclick();dispatch(element('view'),'click',cornerA);assert.equal(vm.runInContext('zoneCorners.length',context),0);assert.match(element('zoneinfo').textContent,/No visible surface/);assert.equal(vm.runInContext('pitch',context),Math.PI/4,'Empty click never changes camera');
vm.runInContext('pitch=-Math.PI/4;orbitMode=true;moved=0',context);const orbitView=vm.runInContext('JSON.stringify({eye,yaw,pitch,orbitMode})',context);element('zonebox').onclick();assert.equal(vm.runInContext('JSON.stringify({eye,yaw,pitch,orbitMode})',context),orbitView,'Orbit POV also retained');
vm.runInContext('orbitOrtho=true;moved=0',context);element('zonebox').onclick();dispatch(element('view'),'click',cornerA);assert.equal(vm.runInContext('zoneCornerWorld[0][2]',context),0,'Orthographic orbit samples actual floor, not behind-camera height plane');
vm.runInContext('orbitMode=false;inspectAbove();moved=0',context);const orthoView=vm.runInContext('JSON.stringify({eye,yaw,pitch,overhead,overheadScale})',context);element('zonebox').onclick();for(const e of [cornerA,cornerB])dispatch(element('view'),'click',e);assert.equal(vm.runInContext('exclusionZones.length',context),2);assert.equal(vm.runInContext('JSON.stringify({eye,yaw,pitch,overhead,overheadScale})',context),orthoView,'Existing orthographic plane semantics retained');
console.log('PASS016 registered Draw box: fly/orbit camera and display preserved, visible surface corners/ghost preview, finite exact volume JSON, Min/MaxZ retained, undo/redo/export/reload, empty-hit feedback, explicit overhead behavior unchanged. GPU appearance unverified.');

// Regression017: selection polycount is immediate in the bottom selection strip.
element('filterdensity').checked=false;element('terraincull').checked=false;element('demo').onclick();vm.runInContext('eye=[0,-30,0];yaw=Math.PI/2;pitch=0;overhead=false;document.pointerLockElement=canvas;moved=0',context);dispatch(element('view'),'pointerdown',pointer);dispatchWindow('pointerup');dispatch(element('view'),'click',pointer);assert.match(element('selectionstatus').textContent,/Selected Synthetic cube.*6 faces \(polygons\).*12 fan triangles/);assert.equal(element('selectionstatus').style.display,'block','Immediate count without render/frame');
element('filterdensity').checked=true;vm.runInContext('updateSelectedFooter()',context);assert.match(element('selectionstatus').textContent,/6 faces/);assert.match(element('selectionstatus').textContent,/before density display filtering/);vm.runInContext('select(-1)',context);assert.equal(element('selectionstatus').textContent,'');assert.equal(element('selectionstatus').style.display,'none');element('demo').onclick();
context.noPolygons=scene();delete context.noPolygons.objects[1].polygons;delete context.noPolygons.objects[1].storedFaceRange;context.noPolygons.objects[1].faceCount=7;vm.runInContext('load(noPolygons);select(1)',context);assert.match(element('selectionstatus').textContent,/7 faces \(reported metadata\)/);
context.previewSelection=scene();vm.runInContext('load(previewSelection);select(1);document.getElementById("terraincull").checked=true;updateTerrainPreview()',context);assert.match(element('selectionstatus').textContent,/Original 1 \/ current 0 faces.*reduction 1/);element('terraincull').checked=false;vm.runInContext('updateTerrainPreview()',context);assert.match(element('selectionstatus').textContent,/1 faces/);assert(!element('selectionstatus').textContent.includes('current 0'));
context.ranges=scene([{x:0,z:5,model:1,range:10},{x:20,z:5,model:120,range:20},{x:40,z:5,model:120,range:21}]);for(let i=1;i<4;i++){context.ranges.objects[i].entityIndex=7;context.ranges.objects[i].reference='same-placement';if(i>1)context.ranges.objects[i].renderPool={model:120,parent_model:1,relative_range:[i-2,1]};}
vm.runInContext('load(ranges);select(3)',context);assert.match(element('selectionstatus').textContent,/3 faces.*whole entity placement.*3 render batches.*active batch model \*120: 1 faces.*active pool range 1:1/);context.selectedRangeSession=JSON.parse(vm.runInContext('JSON.stringify(sessionDocument())',context));vm.runInContext('select(-1);applyInspectionImport(selectedRangeSession,"session")',context);assert.equal(vm.runInContext('selected',context),3,'Session restores exact pool range');assert.match(element('selectionstatus').textContent,/active pool range 1:1/);
console.log('PASS017 immediate selection footer: registered cube click 6polygons/12triangles, explicit metadata fallback, clear selection, preview original/current/reduction, full counts before density filter, whole placement plus active pool batch, exact-range session restore; no per-frame geometry recount.');

// Regression018: canonical LAND receiver is explicitly tagged, at arbitrary model and reordered object index.
context.tagged=scene();const land=context.tagged.objects[0];land.model=47;land.entityIndex=20;land.reference='canonical_land_diagnostic';land.entityClassname='aw_render_diagnostic';land.terrainRole='canonical_land';land.inspectorOnlyDiagnostic=true;const taggedWater=JSON.parse(JSON.stringify(land));taggedWater.name='World taggedWater';taggedWater.model=0;taggedWater.entityIndex=0;taggedWater.reference='';taggedWater.entityClassname='worldspawn';taggedWater.terrainRole='world_legacy';taggedWater.inspectorOnlyDiagnostic=false;taggedWater.storedFaceRange=[100,2];for(const f of taggedWater.polygons){f.texture=2;f.texinfo=2;}context.tagged.textures.push({name:'*water',width:1,height:1,pixels:[90]});context.tagged.objects=[context.tagged.objects[1],taggedWater,land];context.tagged.objects[0].entityIndex=21;
const reordered=JSON.stringify(context.tagged);context.taggedPreview=JSON.parse(vm.runInContext('JSON.stringify(computeTerrainPreview(tagged,0))',context));assert.equal(context.taggedPreview.groundTriangles,2);assert.equal(context.taggedPreview.checkPerformed,true);assert.equal(context.taggedPreview.masks[0][0],true,'Buried placed face culled against tagged model47');assert(context.taggedPreview.masks[1].every(v=>!v),'Water retained');assert(context.taggedPreview.masks[2].every(v=>!v),'Canonical receiver never culls itself');assert.equal(JSON.stringify(context.tagged),reordered,'Role discovery preserves input');
vm.runInContext('load(tagged)',context);element('terrain').checked=false;assert.equal(vm.runInContext('visible(objects[0],0)',context),true);assert.equal(vm.runInContext('visible(objects[1],1)',context),false,'World taggedWater hidden with world category');assert.equal(vm.runInContext('visible(objects[2],2)',context),false,'Tagged canonical LAND hidden independently of model ID');element('terrain').checked=true;
vm.runInContext('render()',context);assert.match(element('status').textContent,/3 render batches.*2 distinct entity placements.*1 world batches/);assert.match(element('status').textContent,/inspector diagnostic geometry present/);
context.noReceiver=JSON.parse(JSON.stringify(context.tagged));context.noReceiver.objects=context.noReceiver.objects.slice(0,2);vm.runInContext('load(noReceiver);document.getElementById("terraincull").checked=true;updateTerrainPreview();terrainPreviewStatus()',context);assert.equal(vm.runInContext('terrainPreview.checkPerformed',context),false);assert.equal(vm.runInContext('previewEnabled()',context),false);assert.match(element('terrainpreviewinfo').textContent,/Terrain unavailable; check not performed/);assert.match(element('terrainwarninglabel').textContent,/Terrain unavailable; check not performed/);assert(!element('previewcounts').textContent.includes('reduction 0'));assert.match(element('previewcounts').textContent,/No receiver-based culling check/);
context.taggedAlias=JSON.parse(JSON.stringify(context.tagged));delete context.taggedAlias.objects[2].terrainRole;context.taggedAlias.objects[2].terrain_role='canonical_land';assert.equal(vm.runInContext('previewGround(taggedAlias,0).prisms.length',context),2);delete context.taggedAlias.objects[2].terrain_role;assert.equal(vm.runInContext('previewGround(taggedAlias,0).prisms.length',context),2,'Exact diagnostic class/ref metadata derives terrain role');
console.log('PASS018 receiver roles: reordered canonical model47, waterworld0 excluded, receiver self-exclusion, world/terrain visibility, empty receivers explicitly not checked, camel/snake role and exact class/ref provenance, render batch vs entity/world counts, diagnostic native warning; source unchanged.');
if(process.env.AW_MARKUP_BSP){const bytes=fs.readFileSync(process.env.AW_MARKUP_BSP);context.bspBytes=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength);const parsed=JSON.parse(vm.runInContext('JSON.stringify(bsp(bspBytes,"diagnostic.bsp"))',context));const pools=parsed.objects.filter(o=>o.renderPool);assert(pools.length>0);assert(pools.every(o=>Number.isInteger(o.entityIndex)&&o.entityIndex>0&&o.renderPool.relative_range[1]===o.storedFaceRange[1]));context.supplied=parsed;const terrainObjects=parsed.objects.filter(o=>o.terrainRole==='canonical_land');assert(terrainObjects.length===1);const receiverTriangles=vm.runInContext('previewGround(supplied,0).prisms.length',context);assert(receiverTriangles>0);assert.equal(receiverTriangles,terrainObjects[0].polygons.reduce((n,f)=>n+f.vertices.length-2,0));assert(terrainObjects[0].inspectorOnlyDiagnostic);console.log('PASS supplied BSP terrain role: canonical LAND '+terrainObjects[0].model+' /'+terrainObjects[0].faceCount+' polygons/'+receiverTriangles+' triangles; non-hardcoded metadata.');console.log('PASS supplied BSP parser: '+parsed.objects.length+' render objects, '+pools.length+' placed pool ranges with entity and range bindings.');}
// Regression019: one explicit entity group drives count, highlight, isolation and fit.
element('terraincull').checked=false;element('filterdensity').checked=false;element('textures').checked=false;element('overlay').checked=false;element('only').checked=false;
context.groupFixture=scene([{x:0,z:5,model:1,range:10},{x:20,z:5,model:120,range:20},{x:40,z:5,model:120,range:21}]);for(let i=1;i<4;i++){context.groupFixture.objects[i].entityIndex=7;context.groupFixture.objects[i].reference='group-ref';if(i>1)context.groupFixture.objects[i].renderPool={model:120,parent_model:1,relative_range:[i-2,1]};}
const groupedOriginal=JSON.stringify(context.groupFixture);vm.runInContext('load(groupFixture);eye=[40,0,7];yaw=0;pitch=-Math.PI/2;overhead=false;document.pointerLockElement=canvas;moved=0',context);dispatch(element('view'),'pointerdown',pointer);dispatchWindow('pointerup');dispatch(element('view'),'click',pointer);
assert.equal(vm.runInContext('selected',context),3,'Registered click keeps exact active range');assert.match(element('selectionstatus').textContent,/3 faces.*6 fan triangles.*whole entity placement.*3 render batches.*active batch model \*120: 1 faces/);
assert.deepEqual(JSON.parse(vm.runInContext('JSON.stringify(objects.map((o,i)=>selectionContains(i)))',context)),[false,true,true,true]);
element('only').checked=true;assert.deepEqual(JSON.parse(vm.runInContext('JSON.stringify(objects.map((o,i)=>visible(o,i)))',context)),[false,true,true,true]);gpuCalls=[];vm.runInContext('render()',context);assert.equal(gpuCalls.filter(c=>c[0]==='drawArrays'&&c[1]==='LINES').length,3,'Isolation submits all three placement line batches');assert(html.includes("'chosen'),selectionContains(i)?1:0"),'All placement batches get yellow highlight');
element('fit').onclick();assert.equal(vm.runInContext('eye[0]',context),20,'Fit uses whole-group center, not active pool x40');assert.deepEqual(JSON.parse(vm.runInContext('JSON.stringify(selectionBounds())',context)),[[-2,-2,5],[42,2,5]]);
context.groupSession=JSON.parse(vm.runInContext('JSON.stringify(sessionDocument())',context));vm.runInContext('select(-1);applyInspectionImport(groupSession,"session")',context);assert.equal(vm.runInContext('selected',context),3);assert.equal(vm.runInContext('selectionStats().batches',context),3);assert.equal(JSON.stringify(context.groupFixture),groupedOriginal,'Selection does not change face identities or geometry');
element('only').checked=false;element('terraincull').checked=true;vm.runInContext('updateTerrainPreview()',context);assert.match(element('selectionstatus').textContent,/Original 3 \/ current 2 faces.*reduction 1.*display-only preview/);element('terraincull').checked=false;vm.runInContext('updateTerrainPreview()',context);
context.noEntity=JSON.parse(JSON.stringify(context.groupFixture));for(const o of context.noEntity.objects)delete o.entityIndex;vm.runInContext('load(noEntity);select(3)',context);assert.equal(vm.runInContext('selectionStats().batches',context),1);assert.match(element('selectionstatus').textContent,/batch only; no entity ID/);assert.equal(vm.runInContext('selectionContains(2)',context),false,'Same reference and pool model do not infer placement grouping');
context.noReceiverGroup=JSON.parse(JSON.stringify(context.groupFixture));context.noReceiverGroup.textures[0].name='*water';vm.runInContext('load(noReceiverGroup);select(3);document.getElementById("terraincull").checked=true;updateTerrainPreview()',context);assert.equal(vm.runInContext('previewEnabled()',context),false);assert.equal(vm.runInContext('selectionStats().currentFaces',context),3);assert.match(element('selectionstatus').textContent,/Terrain unavailable; check not performed/);element('terraincull').checked=false;
console.log('PASS019 whole-placement selection: registered range click, persistent sum/active batch distinction, grouped highlight/isolation draw submissions/Fit, exact-range session restore, preview group reduction, immutable paint identity and missing-entity batch-only fallback. GPU appearance unverified.');
if(process.env.AW_MARKUP_BSP){vm.runInContext('load(supplied)',context);const grouped=JSON.parse(vm.runInContext('JSON.stringify(Array.from(selectionGroups.values()).map(g=>({key:g.key,indices:g.indices,faces:g.faces,triangles:g.triangles})))',context));assert.equal(grouped.length,226);assert.equal(grouped.filter(g=>g.indices.length>1).length,145);const index=context.supplied.objects.findIndex(o=>String(o.reference)==='321235'&&o.faceCount===162);assert(index>=0);element('objects').value=String(index);element('objects').onchange();assert.equal(vm.runInContext('selectionStats().originalFaces',context),1136);assert.equal(vm.runInContext('selectionStats().originalTriangles',context),1276);assert.equal(vm.runInContext('selectionStats().batches',context),2);assert.match(element('selectionstatus').textContent,/1[,\s]136 faces.*1[,\s]276 fan triangles.*active batch model.*162 faces/);const raw=fs.readFileSync(process.env.AW_MARKUP_BSP),entityOffset=raw.readInt32LE(4),entityLength=raw.readInt32LE(8),modelOffset=raw.readInt32LE(4+14*8),entityText=raw.subarray(entityOffset,entityOffset+entityLength).toString('utf8'),entitiesRaw=Array.from(entityText.matchAll(/\{([^}]*)\}/g),m=>Object.fromEntries(Array.from(m[1].matchAll(/"([^"\n]*)"\s*"([^"\n]*)"/g),p=>[p[1],p[2]])));const rawFaces=new Map();entitiesRaw.forEach((e,i)=>{const match=(e.model||'').match(/^\*(\d+)$/);if(i!==0&&!match)return;const model=i===0?0:Number(match[1]);let count=raw.readInt32LE(modelOffset+model*64+60);for(const pair of (e.aw_render_ranges||'').split(',')){if(pair)count+=Number(pair.split(':')[1]);}if(count>0)rawFaces.set('entity:'+i,count);});assert.equal(rawFaces.size,grouped.length);for(const g of grouped)assert.equal(g.faces,rawFaces.get(g.key),'Every placement count matches raw BSP entity/model/range arithmetic: '+g.key);
console.log('PASS supplied023 grouped selection: 609 batches/226 groups/145 multi-batch placements; ref321235 1136 polygons/1276 triangles across two batches, active162.');}

(async()=>{
 assert.match(html,/>Export all<\/button><button id="copysession"/);
 assert.match(html,/id="sessionstatus"[^>]*aria-live="polite"/);
 context.copyFixture=scene();vm.runInContext('load(copyFixture);eye=[12.125,-3.25,48.75];yaw=.4;pitch=-.2',context);
 const original=JSON.stringify(context.copyFixture);let copied=null,selections=0;
 context.inspectionExportTime=()=>({exported_at_utc:'2026-10-03T20:15:30.123Z',exported_at_local:'2026-10-03T23:15:30.123+03:00',exported_at_timezone:'Europe/Helsinki'});
 context.navigator={clipboard:{writeText:async text=>{copied=text;}}};element('copysessiontext').select=()=>selections++;
 const expected=vm.runInContext('inspectionJSONText(sessionDocument())',context);
 assert.equal(await element('copysession').onclick(),true);assert.equal(copied,expected,'Clipboard uses the exact same session builder/serializer as Export all');assert.match(element('sessionstatus').textContent,/copied to clipboard/);assert.equal(element('copysessionfallback').style.display,'none');assert.equal(element('copysession').disabled,false);
 let doc=JSON.parse(copied);assert.deepEqual(doc.camera.xyz,[12.125,-3.25,48.75]);assert.equal(doc.source_sha256,'a'.repeat(64));assert.equal(doc.program.version,'0.0.28');assert(!('objects' in doc));
 context.navigator={};copied=null;assert.equal(await element('copysession').onclick(),false);assert.equal(element('copysessionfallback').style.display,'block');assert.equal(element('copysessiontext').value,expected);assert.equal(selections,1);assert.match(element('sessionstatus').textContent,/Nothing was copied automatically/);
 context.navigator={clipboard:{writeText:async()=>{throw Error('NotAllowedError');}}};assert.equal(await element('copysession').onclick(),false);assert.equal(element('copysessiontext').value,expected);assert.match(element('sessionstatus').textContent,/NotAllowedError/);assert.equal(element('copysession').disabled,false);
 element('selectsessiontext').onclick();assert.equal(selections,3);element('closesessioncopy').onclick();assert.equal(element('copysessionfallback').style.display,'none');assert.equal(element('copysessiontext').value,'');
 assert.equal(JSON.stringify(context.copyFixture),original,'Copy does not mutate scene');
 vm.runInContext('scene=null',context);assert.equal(await element('copysession').onclick(),false);assert.match(element('sessionstatus').textContent,/Load a source scene/);
 console.log('PASS session copy: identical serializer/current POV/source metadata, API success, unavailable/denied local-file manual fallback, explicit feedback, selected text/close and no source mutation; no real host clipboard access.');
})().catch(error=>{console.error(error);process.exitCode=1;});
