/* SPDX-License-Identifier: GPL-2.0-or-later
 * Generated by tools/town_table.py from config/towns.json and the town
 * configs. Do not edit: change the configs and run tools/town_table.py --write.
 * Row order is the stable save order; extra towns take save IDs from
 * AW_TOWN_MAP_BASE, town interiors (towns in row order, then each
 * list order of its town) from AW_TOWN_INTERIOR_BASE (aw_maps.h). */
#ifndef AW_TOWN_TABLE_H
#define AW_TOWN_TABLE_H
#define AW_TOWN_COUNT 10
#define AW_TOWN_FIXED_COUNT 2
#define AW_TOWN_EXTRA_COUNT 8
#define AW_TOWN_EXTRA_NAMES {"vivec_arena","vivec_foreign","vivec_hlaalu","vivec_redoran","vivec_telvanni","vivec_temple","vivec_delyn","vivec_olms"}
#define AW_TOWN_EXTRA_TITLES {"Vivec, Arena","Vivec, Foreign Quarter","Vivec, Hlaalu","Vivec, Redoran","Vivec, Telvanni","Vivec, Temple","Vivec, St. Delyn","Vivec, St. Olms"}
#define AW_TOWN_INTERIOR_COUNT 144
#define AW_TOWN_INTERIOR_NAMES {\
    "vai000","vqi000","vqi001","vqi002","vqi003","vqi004","vqi005","vqi006",\
    "vqi007","vqi008","vqi009","vqi010","vqi011","vqi012","vqi013","vqi014",\
    "vqi015","vqi016","vqi017","vqi018","vqi019","vhi000","vhi001","vhi002",\
    "vhi003","vhi004","vhi005","vhi006","vhi007","vhi008","vhi009","vhi010",\
    "vhi011","vhi012","vhi013","vhi014","vhi015","vhi016","vhi017","vri000",\
    "vri001","vri002","vri003","vri004","vri005","vri006","vri007","vri008",\
    "vri009","vri010","vri011","vri012","vri013","vri014","vri015","vti000",\
    "vti001","vti002","vti003","vti004","vti005","vti006","vti007","vti008",\
    "vti009","vti010","vti011","vti012","vti013","vti014","vti015","vti016",\
    "vti017","vpi000","vpi001","vpi002","vpi003","vpi004","vpi005","vpi006",\
    "vpi007","vpi008","vpi009","vpi010","vpi011","vpi012","vpi013","vpi014",\
    "vpi015","vpi016","vpi017","vpi018","vpi019","vpi020","vpi021","vdi000",\
    "vdi001","vdi002","vdi003","vdi004","vdi005","vdi006","vdi007","vdi008",\
    "vdi009","vdi010","vdi011","vdi012","vdi013","vdi014","vdi015","vdi016",\
    "vdi017","vdi018","vdi019","vdi020","vdi021","voi000","voi001","voi002",\
    "voi003","voi004","voi005","voi006","voi007","voi008","voi009","voi010",\
    "voi011","voi012","voi013","voi014","voi015","voi016","voi017","voi018",\
    "voi019","voi020","voi021","voi022","voi023","voi024","voi025","voi026"\
}
#define AW_TOWN_INTERIOR_TITLES {\
    "Vivec, Arena Pit",\
    "Ibishammus, Shrine",\
    "Vivec, Agrippina Herennia: Clothier",\
    "Vivec, Alusaron: Smith",\
    "Vivec, Andilu Drothan: Alchemist",\
    "Vivec, Aurane Frernis: Apothecary",\
    "Vivec, Black Shalk Cornerclub",\
    "Vivec, Foreign Quarter Canalworks",\
    "Vivec, Foreign Quarter Lower Waistworks",\
    "Vivec, Foreign Quarter Plaza",\
    "Vivec, Foreign Quarter Tomb",\
    "Vivec, Foreign Quarter Underworks",\
    "Vivec, Foreign Quarter Upper Waistworks",\
    "Vivec, Guild of Fighters",\
    "Vivec, Guild of Mages",\
    "Vivec, J'Rasha: Healer",\
    "Vivec, Jeanne: Trader",\
    "Vivec, Jobasha's Rare Books",\
    "Vivec, Miun-Gei: Enchanter",\
    "Vivec, Ralen Tilvur: Smith",\
    "Vivec, Simine Fralinie: Bookseller",\
    "Vivec, Curio Manor",\
    "Vivec, Elven Nations Cornerclub",\
    "Vivec, Hlaalu Alchemist",\
    "Vivec, Hlaalu Ancestral Vaults",\
    "Vivec, Hlaalu Canalworks",\
    "Vivec, Hlaalu Edryno Arethi's House",\
    "Vivec, Hlaalu General Goods",\
    "Vivec, Hlaalu Pawnbroker",\
    "Vivec, Hlaalu Plaza",\
    "Vivec, Hlaalu Prison Cells",\
    "Vivec, Hlaalu Records",\
    "Vivec, Hlaalu Temple",\
    "Vivec, Hlaalu Treasury",\
    "Vivec, Hlaalu Underworks",\
    "Vivec, Hlaalu Vaults",\
    "Vivec, Hlaalu Waistworks",\
    "Vivec, Hlaalu Weaponsmith",\
    "Vivec, No Name Club",\
    "Vivec, Dralor Manor",\
    "Vivec, Redoran Ancestral Vaults",\
    "Vivec, Redoran Canalworks",\
    "Vivec, Redoran Plaza",\
    "Vivec, Redoran Prison Cells",\
    "Vivec, Redoran Records",\
    "Vivec, Redoran Scout & Drillmaster",\
    "Vivec, Redoran Smith",\
    "Vivec, Redoran Temple Shrine",\
    "Vivec, Redoran Trader",\
    "Vivec, Redoran Treasury",\
    "Vivec, Redoran Underworks",\
    "Vivec, Redoran Vaults",\
    "Vivec, Redoran Waistworks",\
    "Vivec, Saren Manor",\
    "Vivec, The Flowers of Gold",\
    "Vivec, Hlaren Residence",\
    "Vivec, Telvanni Alchemist",\
    "Vivec, Telvanni Apothecary",\
    "Vivec, Telvanni Canalworks",\
    "Vivec, Telvanni Enchanter",\
    "Vivec, Telvanni Mage",\
    "Vivec, Telvanni Monster Lab",\
    "Vivec, Telvanni Plaza",\
    "Vivec, Telvanni Prison Cells",\
    "Vivec, Telvanni Sorcerer",\
    "Vivec, Telvanni Temple",\
    "Vivec, Telvanni Tower",\
    "Vivec, Telvanni Underworks",\
    "Vivec, Telvanni Upper Storage",\
    "Vivec, Telvanni Vault",\
    "Vivec, Telvanni Waistworks",\
    "Vivec, Temporary Telvanni Housing",\
    "Vivec, The Lizard's Head",\
    "Ministry of Truth, Hall of Processing",\
    "Ministry of Truth, Holding Cells",\
    "Ministry of Truth, Prison Keep",\
    "Vivec, Canon Offices",\
    "Vivec, Canon Quarters",\
    "Vivec, Hall Underworks",\
    "Vivec, Hall of Justice",\
    "Vivec, Hall of Justice Secret Library",\
    "Vivec, Hall of Wisdom",\
    "Vivec, High Fane",\
    "Vivec, Justice Offices",\
    "Vivec, Library of Vivec",\
    "Vivec, Milo's Quarters",\
    "Vivec, Office of the Watch",\
    "Vivec, Ordinator Barracks",\
    "Vivec, Palace of Vivec",\
    "Vivec, Puzzle Canal, Center",\
    "Vivec, Puzzle Canal, Level 1",\
    "Vivec, Puzzle Canal, Level 2",\
    "Vivec, Puzzle Canal, Level 3",\
    "Vivec, Puzzle Canal, Level 4",\
    "Vivec, Puzzle Canal, Level 5",\
    "Ihinipalit, Shrine",\
    "Vivec, Lucretinaus Olcinius: Trader",\
    "Vivec, Mevel Fererus: Trader",\
    "Vivec, St. Delyn Canal North-One",\
    "Vivec, St. Delyn Canal North-Three",\
    "Vivec, St. Delyn Canal North-Two",\
    "Vivec, St. Delyn Canal South-One",\
    "Vivec, St. Delyn Canal South-Three",\
    "Vivec, St. Delyn Canal South-Two",\
    "Vivec, St. Delyn Canalworks",\
    "Vivec, St. Delyn Glassworker's Hall",\
    "Vivec, St. Delyn Plaza",\
    "Vivec, St. Delyn Potter's Hall",\
    "Vivec, St. Delyn Storage",\
    "Vivec, St. Delyn Underworks",\
    "Vivec, St. Delyn Waist North-One",\
    "Vivec, St. Delyn Waist North-Two",\
    "Vivec, St. Delyn Waist South-One",\
    "Vivec, St. Delyn Waist South-Two",\
    "Vivec, St. Delyn Waistworks",\
    "Vivec, Tervur Braven: Trader",\
    "Vivec, The Abbey of St. Delyn the Wise",\
    "Assernerairan, Shrine",\
    "Vivec, St. Olms Brewers and Fishmongers Hall",\
    "Vivec, St. Olms Canal North-One",\
    "Vivec, St. Olms Canal North-Three",\
    "Vivec, St. Olms Canal North-Two",\
    "Vivec, St. Olms Canal South-One",\
    "Vivec, St. Olms Canal South-Three",\
    "Vivec, St. Olms Canal South-Two",\
    "Vivec, St. Olms Canalworks",\
    "Vivec, St. Olms Farmers and Laborers Hall",\
    "Vivec, St. Olms Haunted Manor",\
    "Vivec, St. Olms Plaza",\
    "Vivec, St. Olms Storage",\
    "Vivec, St. Olms Tailors and Dyers Hall",\
    "Vivec, St. Olms Tanners and Miners Hall",\
    "Vivec, St. Olms Temple",\
    "Vivec, St. Olms Underworks",\
    "Vivec, St. Olms Upper North-One",\
    "Vivec, St. Olms Upper North-Two",\
    "Vivec, St. Olms Upper South-One",\
    "Vivec, St. Olms Waist North-One",\
    "Vivec, St. Olms Waist North-Two",\
    "Vivec, St. Olms Waist South-One",\
    "Vivec, St. Olms Waist South-Two",\
    "Vivec, St. Olms Waistworks",\
    "Vivec, St. Olms Yngling Manor",\
    "Vivec, St. Olms Yngling Manor Basement"\
}
/* Town row (AW_Town index) whose door bank leads into each interior. */
#define AW_TOWN_INTERIOR_TOWNS {\
    2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4,\
    4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,6,6,\
    6,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,8,\
    8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,9,9,9,9,9,9,9,9,9,9,9,\
    9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9\
}
/* name,title,prefix,regions,travel_npc,travel_target,region_cap,draw_distance,
   world_slot,flags,travel_return,handoff,origin[3],core[4] */
#define AW_TOWN_ROWS {\
    {"seyda","Seyda Neen","sn","seyda-regions.txt","Darvame Hleran","balmora",64,540,0,AW_TOWN_SEYDA_SCENES|AW_TOWN_LEGACY_PAYLOAD,0,0,{0,0,0},{0,0,0,0}},\
    {"balmora","Balmora","bm","balmora-regions.txt","Selvil Sareloth","seyda",64,540,1,AW_TOWN_OWN_DOORS|AW_TOWN_SCENERY|AW_TOWN_TELEPORT|AW_TOWN_GROUND_PLACE,1,0,{0,0,0},{0,0,0,0}},\
    {"vivec_arena","Vivec, Arena","va","vivec_arena-regions.txt","","",64,540,-1,AW_TOWN_OWN_DOORS|AW_TOWN_SCENERY|AW_TOWN_TELEPORT|AW_TOWN_GROUND_PLACE,0,1,{9088,-21760,0},{-1440,-1440,1440,1440}},\
    {"vivec_foreign","Vivec, Foreign Quarter","vq","vivec_foreign-regions.txt","","",64,540,-1,AW_TOWN_OWN_DOORS|AW_TOWN_SCENERY|AW_TOWN_TELEPORT|AW_TOWN_GROUND_PLACE,0,1,{8192,-19456,0},{-2048,-1024,2048,1024}},\
    {"vivec_hlaalu","Vivec, Hlaalu","vh","vivec_hlaalu-regions.txt","","",64,540,-1,AW_TOWN_OWN_DOORS|AW_TOWN_SCENERY|AW_TOWN_TELEPORT|AW_TOWN_GROUND_PLACE,0,1,{5120,-21120,0},{-1024,-1408,1024,1408}},\
    {"vivec_redoran","Vivec, Redoran","vr","vivec_redoran-regions.txt","","",64,540,-1,AW_TOWN_OWN_DOORS|AW_TOWN_SCENERY|AW_TOWN_TELEPORT|AW_TOWN_GROUND_PLACE,0,1,{7168,-21504,0},{-1024,-1024,1024,1024}},\
    {"vivec_telvanni","Vivec, Telvanni","vt","vivec_telvanni-regions.txt","","",64,540,-1,AW_TOWN_OWN_DOORS|AW_TOWN_SCENERY|AW_TOWN_TELEPORT|AW_TOWN_GROUND_PLACE,0,1,{11264,-21120,0},{-1024,-1408,1024,1408}},\
    {"vivec_temple","Vivec, Temple","vp","vivec_temple-regions.txt","","",64,540,-1,AW_TOWN_OWN_DOORS|AW_TOWN_SCENERY|AW_TOWN_TELEPORT|AW_TOWN_GROUND_PLACE,0,1,{8192,-26112,0},{-1536,-1536,1536,1536}},\
    {"vivec_delyn","Vivec, St. Delyn","vd","vivec_delyn-regions.txt","","",64,540,-1,AW_TOWN_OWN_DOORS|AW_TOWN_SCENERY|AW_TOWN_TELEPORT|AW_TOWN_GROUND_PLACE,0,1,{7168,-23552,0},{-1024,-1024,1024,1024}},\
    {"vivec_olms","Vivec, St. Olms","vo","vivec_olms-regions.txt","","",64,540,-1,AW_TOWN_OWN_DOORS|AW_TOWN_SCENERY|AW_TOWN_TELEPORT|AW_TOWN_GROUND_PLACE,0,1,{9216,-23552,0},{-1024,-1024,1024,1024}}\
}
#endif
