# SPDX-License-Identifier: GPL-3.0-only
"""CHIM Cell Tracker page: docs/chim/CELL_TRACKER.md, generated from the tracker data (cell_progress.py render-md).

The page is compact: headline, totals, per-ring table, failures by mechanism class, per-object-type table and the import
policy. The policy section is built from the constants of cell_progress.py so it cannot drift from the code. Per-cell
detail stays in the Toolkit and its CSV export. Nothing here reads game data or private paths.
"""
import collections
import datetime
import re

import cell_lighting as lt
import cell_progress as cp

HEADER = '<!-- GENERATED by tools/cell_progress.py render-md. Do not edit by hand: change the code or the tracker data. -->'
MAIN_ISLAND = 1

# What each status means (display order). Keys are the tracker's buckets.
STATUS_TEXT = collections.OrderedDict([
    ('complete', '%s: terrain and every placed object converted, actors included, all measured audits passed, and the cell '
                 'lit like the original (lighting audit: lit).' % cp.COMPLETE_LABEL),
    ('terrain_complete', ('%s: all measured audits passed and every placed object except actors converted (statics, flora, '
                         'lights, doors, containers, activators, items%s); actors may still be deferred.' %
                         (cp.TERRAIN_COMPLETE_LABEL, ', markers' if cp.MARKERS_BLOCK_COMPLETE else '')) +
                         ('' if cp.MARKERS_BLOCK_COMPLETE else ' Nonvisual markers are not required.') +
                         (' The cell must also be lit like the original (lighting audit: lit).' if cp.LIGHTING_REQUIRED else '')),
    ('complete_unlit', '%s: everything %s needs except the lighting audit (lit). Counts as done; becomes %s once '
                       'lit.' % (cp.COMPLETE_UNLIT_LABEL, cp.COMPLETE_LABEL.lower(), cp.COMPLETE_LABEL.lower())),
    ('terrain_complete_unlit', '%s: everything %s needs except the lighting audit (lit). Counts as done; becomes %s '
                               'once lit.' % (cp.TERRAIN_COMPLETE_UNLIT_LABEL, cp.TERRAIN_COMPLETE_LABEL.lower(),
                                              cp.TERRAIN_COMPLETE_LABEL.lower())),
    ('audits_passed', 'Passed: converted and every measured audit passed, but something placed is still deferred or skipped '
                      '(owner-approved and playtested cells also count here).'),
    ('empty_sea', 'Empty sea: terrain and water only, nothing placed. Counts as done.'),
    ('hull_policy_pending', 'Hull policy pending: converted; the only problem is a standing-hull chain deeper than the limit '
                            'below, waiting for one shared routing rule. Neither passed nor failed.'),
    ('converted_failing', 'Failed: converted, but at least one audit failed or the conversion reported an error.'),
    ('not_converted', 'Not converted: the conversion was tried and could not finish the cell (for example an object placed '
                      'across a cell edge). A failure-type state, never counted as done.'),
    ('not_started', 'Not started: the conversion has not reached the cell yet.'),
])

# Pass criterion of each audit (what "passed" means). Limits come from the constants of cell_progress.py.
AUDIT_CRITERIA = {
    'format_validation': 'The world-format validator reports 0 failures.',
    'stair_walk': 'Every step of every stair flight in the cell can be walked.',
    'memory_fit': 'The zone ring and the frame heap fit their budgets, with headroom, at every point of the cell.',
    'seam_tears': 'No terrain or hull seam tears.',
    'hull_bevels': 'No standing-hull chain with a depth of %d or more.' % cp.HULL_CHAIN_DEPTH_LIMIT,
    'sky_bank_texels': 'No texture has texels on the sky bank.',
    'hidden_faces': 'No hidden faces left in the converted meshes (no CHIM audit measures this yet).',
    'far_terrain': 'The far-terrain layer covers the cell with no coverage failures.',
    'sprite_shape': 'Sprites keep their real outline (transparent texels skipped, no solid rectangles).',
    'actor_grounding': 'Every actor stands on ground (measured by the actor pipeline; not measured while actors are deferred).',
    'door_links': 'Every door converts and links to its destination.',
}

DEFERRED_TEXT = [
    ('Statics, flora, containers, activators, items, doors and lights', 'converted by the cell conversion.'),
    ('Lights without a mesh (plain lights, glowing plants, darkeners, fires)',
     'not placed as models: judged by the lighting audit (baked as Quake light entities, or not represented). They keep '
     'a cell from both completion levels until it is lit.' if cp.LIGHTING_REQUIRED else 'deferred lights.'),
    ('NPCs', 'deferred to the actor pipeline (resident conversion).'),
    ('Creatures and leveled creatures', 'deferred to the actor pipeline (creature simulation pending).'),
    ('Nonvisual source markers (door, travel, north and editor markers)',
     'not drawn, not required: never block a completion level; door destinations come from the door records.'
     if not cp.MARKERS_BLOCK_COMPLETE else 'deferred: nothing to draw, so not converted.'),
    ('References outside the cell frame', 'skipped in this cell: the neighbouring cell frame that contains them places them.'),
]


def n(v):
    return '{:,}'.format(int(v))


def pct(a, b):
    return '%.1f %%' % (100.0 * a / b) if b else '0.0 %'


def table(head, rows, right_from=1):
    out = ['| ' + ' | '.join(head) + ' |',
           '| ' + ' | '.join(':--' if i < right_from else '--:' for i in range(len(head))) + ' |']
    out += ['| ' + ' | '.join(str(c) for c in r) + ' |' for r in rows]
    return out


def island_cells(doc, island):
    return [c for c in doc['cells'].values() if c.get('island') == island and (c['land'] or c['chim']['bucket'] == 'empty_sea')]


def classes(cells):
    """Counts of the page's status classes over cells (owner states fold into Passed)."""
    c = collections.Counter(r['chim']['bucket'] for r in cells)
    return collections.OrderedDict([
        ('complete', c['complete']),
        ('terrain_complete', c['terrain_complete']),
        ('complete_unlit', c['complete_unlit']),
        ('terrain_complete_unlit', c['terrain_complete_unlit']),
        ('audits_passed', c['audits_passed'] + c['approved'] + c['playtested']),
        ('empty_sea', c['empty_sea']),
        ('hull_policy_pending', c['hull_policy_pending']),
        ('converted_failing', c['converted_failing'] + c['converted_unmeasured']),
        ('not_converted', c['not_converted']),
        ('not_started', c['not_started'])])


def lighting_lines(cells):
    """The island-wide lighting line and the light placements by class (land cells)."""
    h = lt.headline([c['lighting'] for c in cells if c['land'] and c.get('lighting')])
    st = h['status']
    out = ['Lighting: lit %s, partial %s, unlit %s, not measured %s (cells; lit is required for both completion levels).' %
           tuple(n(st[k]) for k in lt.STATUSES)]
    if h['lights']:
        parts = ['%s %s (%s without a mesh)' % (lt.CLASS_LABELS[k], n(v['mesh'] + v['meshless']), n(v['meshless']))
                 for k, v in h['lights'].items()]
        r = h['reach']
        out += ['', 'Original lights in these cells: ' + ', '.join(parts) + '. In converted cells: %s baked, %s night lamps only, '
                '%s not represented.' % (n(r['baked']), n(r['lamp_table']), n(r['none']))]
    return out


def policy_lines():
    out = ['## Import policy', '',
           'Generated from the constants of the tracker code, so it cannot drift from what the tracker does.', '',
           '### What the statuses mean', '']
    out += ['- ' + t for t in STATUS_TEXT.values()]
    out += ['', 'Done = %s + %s + %s + %s + passed + empty sea, each kept on its own line. Empty sea cells count as done: '
            'there is nothing to convert there but the terrain and the water.' % (
                cp.COMPLETE_LABEL.lower(), cp.TERRAIN_COMPLETE_LABEL.lower(), cp.COMPLETE_UNLIT_LABEL.lower(),
                cp.TERRAIN_COMPLETE_UNLIT_LABEL.lower()), '',
            'Eligible for %s = every done cell: %s, %s, %s, %s, passed (owner-approved and playtested included) and '
            'empty sea (it passes as it is; the open world needs the water around the coast). Lighting does not have to '
            'be done.' % (
                cp.ELIGIBLE_RELEASE, cp.COMPLETE_LABEL.lower(), cp.TERRAIN_COMPLETE_LABEL.lower(),
                cp.COMPLETE_UNLIT_LABEL.lower(), cp.TERRAIN_COMPLETE_UNLIT_LABEL.lower()), '',
            'Status precedence, strongest first: %s > %s > %s > %s > passed > hull policy pending > failed > not converted > '
            'not started.' % (cp.COMPLETE_LABEL.lower(), cp.TERRAIN_COMPLETE_LABEL.lower(), cp.COMPLETE_UNLIT_LABEL.lower(),
                              cp.TERRAIN_COMPLETE_UNLIT_LABEL.lower()),
            '', '### Audits and their pass criteria', '']
    out += table(['Audit', 'Passes when'], [(cp.MECHANISMS[k], AUDIT_CRITERIA[k]) for k in cp.MECHANISMS], right_from=2)
    out += ['', 'An audit that was not measured is never counted as passed. Hull chain depth limit: %d.' % cp.HULL_CHAIN_DEPTH_LIMIT,
            '', '### Converted and deferred', '']
    out += table(['Object', 'Handling'], DEFERRED_TEXT, right_from=2)
    out += ['', '### Lighting', '', 'A cell is only complete when it is lit like the original. The lighting audit compares the '
            'original light placements of the cell (by class, with and without a mesh) with what the CHIM build lit:']
    out += [''] + ['- ' + t for t in lt.STATUS_TEXT.values()]
    out += ['', 'A light reaches the frame baked (a light entity in the lightmaps, animated by its lightstyle), through the night '
            'lamp table (dynamic light at night only, the nearest few lamps: partial), or not at all. A surface is lit when it '
            'carries real light data; one constant value for a whole terrain chunk, or no lightmap at all, is not lit. Lights '
            'flagged Off by default give no light in the original either and are not counted. Builds from before the lighting '
            'figures are read as lighting mode "%s" (constant terrain light, models without lightmaps, night lamp table).'
            % lt.ASSUMED_MODE]
    out += ['', 'Object categories in the table above: ' + ', '.join(cp.CATEGORIES.values()) + '. A deferred or skipped '
            'object keeps its cell from being %s (actors: from being %s).' %
            (cp.TERRAIN_COMPLETE_LABEL.lower(), cp.COMPLETE_LABEL.lower()),
            '', 'The island-wide conversion tool that fills this page (CHIMport) comes with the next release.']
    return out


def release_lines(doc):
    """Per-release table: which cells the owner approved for which release, and how they stand."""
    rows = doc.get('releases') or []
    out = ['## Releases', '',
           'Which cells are approved for which release (set by the owner with `cell_progress.py release`; conversion results '
           'never change it).', '']
    if not any(r['approved'] for r in rows if r['release']):
        return out + ['No cells are assigned to a release yet.', '']
    body = [(r['release'] or 'unassigned', 'shipped' if r['shipped'] else ('open' if r['release'] else '-'), n(r['approved']),
             n(r['complete']), n(r['awaiting_lighting']), n(r['lit']), n(r['empty_sea']), n(r['failing']),
             n(r['hull_policy_pending'])) for r in rows if r['approved']]
    return out + table(['Release', 'State', 'Cells', 'Complete', 'Awaiting lighting', 'Lit', 'Empty sea', 'Failing',
                        'Hull policy pending'], body) + ['']


def category_lines(group):
    cats = (group or {}).get('by_category') or {}
    if not any(c['placed'] for c in cats.values()):
        return ['Per object type: not recorded yet.']
    note = ['', 'Counts are every placed reference in converted cells, from the conversion job. Door and light figures in the '
            'Toolkit contents panel (original census) and the door audit (links per cell) are different measures. Light emitters '
            'without a mesh stay under Lights: they cast light, so the lighting audit keeps a cell from both completion levels '
            'until it is lit.']
    rows, reasons = [], []
    for k, label in cp.CATEGORIES.items():
        c = cats.get(k) or cp.new_category()
        if not c['placed'] and not c['converted']:
            if k == 'flora':
                rows.append((label, 'not recorded by type (counted inside statics)', '', '', '', ''))
            continue
        d, s = sum(c['deferred'].values()), sum(c['skipped'].values())
        if k == 'markers' and not cp.MARKERS_BLOCK_COMPLETE:
            rows.append((label, n(c['placed']), 'not drawn, not required', '-', '-', '-'))
            continue
        if k == 'flora':
            rows.append((label, n(c['placed']), 'in statics', '-', '-', '-'))
            continue
        rows.append((label, n(c['placed']), n(c['converted']), n(d), n(s), n(c['failed'])))
        for kind, dd in (('deferred', c['deferred']), ('skipped', c['skipped'])):
            for reason in sorted(dd):
                reasons.append('- %s, %s: %s (%s)' % (label, kind, reason, n(dd[reason])))
    out = table(['Object type', 'Placed', 'Converted', 'Deferred', 'Skipped', 'Failed'], rows)
    return out + ([''] + reasons if reasons else []) + note


def render(doc, today=None):
    """The page text (LF, no trailing whitespace) for one aw-cell-progress-1 document."""
    today = today or datetime.datetime.now().astimezone().strftime('%Y-%m-%d %H:%M %z')
    cells = island_cells(doc, MAIN_ISLAND)
    total = len(cells)
    cl = classes(cells)
    done = sum(cl[k] for k in cp.COMPLETE_LEVELS) + cl['audits_passed'] + cl['empty_sea']
    eligible = sum(1 for c in cells if c['chim']['bucket'] in cp.ELIGIBLE)
    out = [HEADER, '', '# CHIM Cell Tracker', '',
           'Live status of the open world on CHIM, Vvardenfell (island %d). Generated page: do not edit by hand. '
           'Per-cell detail is in the Toolkit and its CSV export.' % MAIN_ISLAND, '',
           '**Done: %s of %s (%s)**' % (n(done), n(total), pct(done, total)), '',
           '- %s: %s' % (cp.COMPLETE_LABEL, n(cl['complete'])),
           '- %s: %s' % (cp.TERRAIN_COMPLETE_LABEL, n(cl['terrain_complete'])),
           '- %s: %s' % (cp.COMPLETE_UNLIT_LABEL, n(cl['complete_unlit'])),
           '- %s: %s' % (cp.TERRAIN_COMPLETE_UNLIT_LABEL, n(cl['terrain_complete_unlit'])),
           '- Passed (something still deferred): %s' % n(cl['audits_passed']),
           '- Empty sea: %s' % n(cl['empty_sea']), '',
           '**Eligible for %s: %s of %s** (every done cell, lighting done or not; definition in the import policy).' % (
               cp.ELIGIBLE_RELEASE, n(eligible), n(total)), ''] + lighting_lines(cells) + [
           '',
           'Generated %s. Tracker data generated %s.' % (today, doc.get('generated', 'unknown')), '',
           '## Totals', '']
    labels = {'complete': cp.COMPLETE_LABEL, 'terrain_complete': cp.TERRAIN_COMPLETE_LABEL,
              'complete_unlit': cp.COMPLETE_UNLIT_LABEL, 'terrain_complete_unlit': cp.TERRAIN_COMPLETE_UNLIT_LABEL, 'audits_passed': 'Passed (something still deferred)', 'empty_sea': 'Empty sea',
              'hull_policy_pending': 'Hull policy pending', 'converted_failing': 'Failed',
              'not_converted': 'Not converted', 'not_started': 'Not started'}
    out += table(['Status', 'Cells', 'Share'], [(labels[k], n(v), pct(v, total)) for k, v in cl.items()])
    out += ['', 'Definitions are in the import policy below.', ''] + release_lines(doc)
    out += ['## Per ring (ring 1 touches the sea)', '']
    rings = sorted({c['ring'] for c in cells if c.get('ring') is not None})
    rows = []
    for r in rings:
        rc = classes([c for c in cells if c.get('ring') == r])
        rows.append((r, n(sum(rc.values()))) + tuple(n(rc[k]) for k in cl))
    out += table(['Ring', 'Cells'] + [labels[k] for k in cl], rows)
    out += ['', '## Failures by mechanism class', '']
    fails, plain = collections.Counter(), 0
    for c in cells:
        if c['chim']['bucket'] != 'converted_failing':
            continue
        bad = [m for m, a in c['audits'].items() if a['status'] == 'failed']
        for m in bad:
            fails[m] += 1
        plain += 0 if bad else 1
    if fails or plain:
        rows = [(cp.MECHANISMS.get(m, m), n(fails[m])) for m in cp.MECHANISMS if fails[m]]
        if plain:
            rows.append(('Conversion error (no single failing audit)', n(plain)))
        out += table(['Mechanism', 'Cells'], rows)
        out += ['', 'A cell can fail more than one mechanism. Hull policy pending cells are not failures; they have their own line.']
    else:
        out += ['No failing cells.']
    out += ['', '## Per object type (converted cells, island-wide)', '']
    isl = [g for g in (doc.get('totals') or {}).get('islands', []) if g.get('island') == MAIN_ISLAND]
    out += category_lines(isl[0] if isl else None)
    out += [''] + policy_lines()
    text = '\n'.join(x.rstrip() for x in out) + '\n'
    return text


# Private paths and private volume names; words and tool names are checked by the release scan of the whole tree.
PRIVATE_PATTERNS = (re.compile(r'\b[A-Za-z]:[\\/]'), re.compile(r'(^|[\s(`])/(vol|src|out|owned|trk|met|perf)\b'),
                    re.compile(r'amiwind-[a-z0-9-]*-\d{3}'))


def private_hits(text):
    """Every line of text that looks like a private path, volume name or tool mention."""
    return [ln for ln in text.splitlines() if any(p.search(ln) for p in PRIVATE_PATTERNS)]


def policy_section(text):
    i = text.find('## Import policy')
    return text[i:] if i >= 0 else ''


def check(page_text, doc_for_policy=None):
    """Problems of a committed page: header missing, private content, or an import policy that no longer matches the code."""
    problems = []
    if not page_text.startswith(HEADER):
        problems.append('generated header missing')
    for ln in private_hits(page_text):
        problems.append('private content: ' + ln[:80])
    want = '\n'.join(x.rstrip() for x in policy_lines()) + '\n'
    if policy_section(page_text) != want:
        problems.append('import policy section is stale: run tools/cell_progress.py render-md')
    return problems
