# SPDX-License-Identifier: GPL-3.0-only
"""CHIM Cell Tracker page: docs/chim/CELL_TRACKER.md, generated from the tracker data (cell_progress.py render-md).

The page is compact: headline, totals, per-ring table, failures by mechanism class, per-object-type table and the import
policy. The policy section is built from the constants of cell_progress.py so it cannot drift from the code. Per-cell
detail stays in the Toolkit and its CSV export. Nothing here reads game data or private paths.
"""
import collections
import datetime
import re

import cell_progress as cp

HEADER = '<!-- GENERATED by tools/cell_progress.py render-md. Do not edit by hand: change the code or the tracker data. -->'
MAIN_ISLAND = 1

# What each status means (display order). Keys are the tracker's buckets.
STATUS_TEXT = collections.OrderedDict([
    ('complete', '%s: terrain and every placed object converted, actors included, all measured audits passed.' % cp.COMPLETE_LABEL),
    ('terrain_complete', ('%s: all measured audits passed and every placed object except actors converted (statics, flora, '
                         'lights, doors, containers, activators, items%s); actors may still be deferred.' %
                         (cp.TERRAIN_COMPLETE_LABEL, ', markers' if cp.MARKERS_BLOCK_COMPLETE else '')) +
                         ('' if cp.MARKERS_BLOCK_COMPLETE else ' Nonvisual markers are not required.')),
    ('audits_passed', 'Passed: converted and every measured audit passed, but something placed is still deferred or skipped '
                      '(owner-approved and playtested cells also count here).'),
    ('empty_sea', 'Empty sea: terrain and water only, nothing placed. Counts as done.'),
    ('hull_policy_pending', 'Hull policy pending: converted; the only problem is a standing-hull chain deeper than the limit '
                            'below, waiting for one shared routing rule. Neither passed nor failed.'),
    ('converted_failing', 'Failed: converted, but at least one audit failed or the conversion reported an error.'),
    ('not_converted', 'Not converted: the conversion was tried and could not finish the cell (for example an object placed '
                      'across a cell edge). A failure-type state, never counted as done.'),
    ('not_started', 'Not started: the conversion has not reached the cell yet.'),
])

# Pass criterion of each audit (what "passed" means). Limits come from the constants of cell_progress.py.
AUDIT_CRITERIA = {
    'format_validation': 'The world-format validator reports 0 failures.',
    'stair_walk': 'Every step of every stair flight in the cell can be walked.',
    'memory_fit': 'The zone ring and the frame heap fit their budgets, with headroom, at every point of the cell.',
    'seam_tears': 'No terrain or hull seam tears.',
    'hull_bevels': 'No standing-hull chain with a depth of %d or more.' % cp.HULL_CHAIN_DEPTH_LIMIT,
    'sky_bank_texels': 'No texture has texels on the sky bank.',
    'hidden_faces': 'No hidden faces left in the converted meshes (no CHIM audit measures this yet).',
    'far_terrain': 'The far-terrain layer covers the cell with no coverage failures.',
    'sprite_shape': 'Sprites keep their real outline (transparent texels skipped, no solid rectangles).',
    'actor_grounding': 'Every actor stands on ground (measured by the actor pipeline; not measured while actors are deferred).',
    'door_links': 'Every door converts and links to its destination.',
}

DEFERRED_TEXT = [
    ('Statics, flora, containers, activators, items, doors and lights', 'converted by the cell conversion.'),
    ('NPCs', 'deferred to the actor pipeline (resident conversion).'),
    ('Creatures and leveled creatures', 'deferred to the actor pipeline (creature simulation pending).'),
    ('Nonvisual source markers (door, travel, north and editor markers)',
     'not drawn, not required: never block a completion level; door destinations come from the door records.'
     if not cp.MARKERS_BLOCK_COMPLETE else 'deferred: nothing to draw, so not converted.'),
    ('References outside the cell frame', 'skipped in this cell: the neighbouring cell frame that contains them places them.'),
]


def n(v):
    return '{:,}'.format(int(v))


def pct(a, b):
    return '%.1f %%' % (100.0 * a / b) if b else '0.0 %'


def table(head, rows, right_from=1):
    out = ['| ' + ' | '.join(head) + ' |',
           '| ' + ' | '.join(':--' if i < right_from else '--:' for i in range(len(head))) + ' |']
    out += ['| ' + ' | '.join(str(c) for c in r) + ' |' for r in rows]
    return out


def island_cells(doc, island):
    return [c for c in doc['cells'].values() if c.get('island') == island and (c['land'] or c['chim']['bucket'] == 'empty_sea')]


def classes(cells):
    """Counts of the page's status classes over cells (owner states fold into Passed)."""
    c = collections.Counter(r['chim']['bucket'] for r in cells)
    return collections.OrderedDict([
        ('complete', c['complete']),
        ('terrain_complete', c['terrain_complete']),
        ('audits_passed', c['audits_passed'] + c['approved'] + c['playtested']),
        ('empty_sea', c['empty_sea']),
        ('hull_policy_pending', c['hull_policy_pending']),
        ('converted_failing', c['converted_failing'] + c['converted_unmeasured']),
        ('not_converted', c['not_converted']),
        ('not_started', c['not_started'])])


def policy_lines():
    out = ['## Import policy', '',
           'Generated from the constants of the tracker code, so it cannot drift from what the tracker does.', '',
           '### What the statuses mean', '']
    out += ['- ' + t for t in STATUS_TEXT.values()]
    out += ['', 'Done = %s + %s + passed + empty sea, each kept on its own line. Empty sea cells count as done: there is nothing '
            'to convert there but the terrain and the water.' % (cp.COMPLETE_LABEL.lower(), cp.TERRAIN_COMPLETE_LABEL.lower()), '',
            'Status precedence, strongest first: %s > %s > passed > hull policy pending > failed > not converted > not started.' %
            (cp.COMPLETE_LABEL.lower(), cp.TERRAIN_COMPLETE_LABEL.lower()),
            '', '### Audits and their pass criteria', '']
    out += table(['Audit', 'Passes when'], [(cp.MECHANISMS[k], AUDIT_CRITERIA[k]) for k in cp.MECHANISMS], right_from=2)
    out += ['', 'An audit that was not measured is never counted as passed. Hull chain depth limit: %d.' % cp.HULL_CHAIN_DEPTH_LIMIT,
            '', '### Converted and deferred', '']
    out += table(['Object', 'Handling'], DEFERRED_TEXT, right_from=2)
    out += ['', 'Object categories in the table above: ' + ', '.join(cp.CATEGORIES.values()) + '. A deferred or skipped '
            'object keeps its cell from being %s (actors: from being %s).' %
            (cp.TERRAIN_COMPLETE_LABEL.lower(), cp.COMPLETE_LABEL.lower()),
            '', 'The island-wide conversion tool that fills this page (CHIMport) comes with the next release.']
    return out


def category_lines(group):
    cats = (group or {}).get('by_category') or {}
    if not any(c['placed'] for c in cats.values()):
        return ['Per object type: not recorded yet.']
    note = ['', 'Counts are every placed reference in converted cells, from the conversion job. Door and light figures in the '
            'Toolkit contents panel (original census) and the door audit (links per cell) are different measures. Light emitters '
            'without a mesh stay under Lights: they cast light, so they keep a cell from being terrain complete.']
    rows, reasons = [], []
    for k, label in cp.CATEGORIES.items():
        c = cats.get(k) or cp.new_category()
        if not c['placed'] and not c['converted']:
            if k == 'flora':
                rows.append((label, 'not recorded by type (counted inside statics)', '', '', '', ''))
            continue
        d, s = sum(c['deferred'].values()), sum(c['skipped'].values())
        if k == 'markers' and not cp.MARKERS_BLOCK_COMPLETE:
            rows.append((label, n(c['placed']), 'not drawn, not required', '-', '-', '-'))
            continue
        if k == 'flora':
            rows.append((label, n(c['placed']), 'in statics', '-', '-', '-'))
            continue
        rows.append((label, n(c['placed']), n(c['converted']), n(d), n(s), n(c['failed'])))
        for kind, dd in (('deferred', c['deferred']), ('skipped', c['skipped'])):
            for reason in sorted(dd):
                reasons.append('- %s, %s: %s (%s)' % (label, kind, reason, n(dd[reason])))
    out = table(['Object type', 'Placed', 'Converted', 'Deferred', 'Skipped', 'Failed'], rows)
    return out + ([''] + reasons if reasons else []) + note


def render(doc, today=None):
    """The page text (LF, no trailing whitespace) for one aw-cell-progress-1 document."""
    today = today or datetime.datetime.now().astimezone().strftime('%Y-%m-%d %H:%M %z')
    cells = island_cells(doc, MAIN_ISLAND)
    total = len(cells)
    cl = classes(cells)
    done = cl['complete'] + cl['terrain_complete'] + cl['audits_passed'] + cl['empty_sea']
    out = [HEADER, '', '# CHIM Cell Tracker', '',
           'Live status of the open world on CHIM, Vvardenfell (island %d). Generated page: do not edit by hand. '
           'Per-cell detail is in the Toolkit and its CSV export.' % MAIN_ISLAND, '',
           '**Done: %s of %s (%s)**' % (n(done), n(total), pct(done, total)), '',
           '- %s: %s' % (cp.COMPLETE_LABEL, n(cl['complete'])),
           '- %s: %s' % (cp.TERRAIN_COMPLETE_LABEL, n(cl['terrain_complete'])),
           '- Passed (something still deferred): %s' % n(cl['audits_passed']),
           '- Empty sea: %s' % n(cl['empty_sea']), '',
           'Generated %s. Tracker data generated %s.' % (today, doc.get('generated', 'unknown')), '',
           '## Totals', '']
    labels = {'complete': cp.COMPLETE_LABEL, 'terrain_complete': cp.TERRAIN_COMPLETE_LABEL, 'audits_passed': 'Passed (something still deferred)', 'empty_sea': 'Empty sea',
              'hull_policy_pending': 'Hull policy pending', 'converted_failing': 'Failed',
              'not_converted': 'Not converted', 'not_started': 'Not started'}
    out += table(['Status', 'Cells', 'Share'], [(labels[k], n(v), pct(v, total)) for k, v in cl.items()])
    out += ['', 'Definitions are in the import policy below.', '', '## Per ring (ring 1 touches the sea)', '']
    rings = sorted({c['ring'] for c in cells if c.get('ring') is not None})
    rows = []
    for r in rings:
        rc = classes([c for c in cells if c.get('ring') == r])
        rows.append((r, n(sum(rc.values()))) + tuple(n(rc[k]) for k in cl))
    out += table(['Ring', 'Cells'] + [labels[k] for k in cl], rows)
    out += ['', '## Failures by mechanism class', '']
    fails, plain = collections.Counter(), 0
    for c in cells:
        if c['chim']['bucket'] != 'converted_failing':
            continue
        bad = [m for m, a in c['audits'].items() if a['status'] == 'failed']
        for m in bad:
            fails[m] += 1
        plain += 0 if bad else 1
    if fails or plain:
        rows = [(cp.MECHANISMS.get(m, m), n(fails[m])) for m in cp.MECHANISMS if fails[m]]
        if plain:
            rows.append(('Conversion error (no single failing audit)', n(plain)))
        out += table(['Mechanism', 'Cells'], rows)
        out += ['', 'A cell can fail more than one mechanism. Hull policy pending cells are not failures; they have their own line.']
    else:
        out += ['No failing cells.']
    out += ['', '## Per object type (converted cells, island-wide)', '']
    isl = [g for g in (doc.get('totals') or {}).get('islands', []) if g.get('island') == MAIN_ISLAND]
    out += category_lines(isl[0] if isl else None)
    out += [''] + policy_lines()
    text = '\n'.join(x.rstrip() for x in out) + '\n'
    return text


# Private paths and private volume names; words and tool names are checked by the release scan of the whole tree.
PRIVATE_PATTERNS = (re.compile(r'\b[A-Za-z]:[\\/]'), re.compile(r'(^|[\s(`])/(vol|src|out|owned|trk|met|perf)\b'),
                    re.compile(r'amiwind-[a-z0-9-]*-\d{3}'))


def private_hits(text):
    """Every line of text that looks like a private path, volume name or tool mention."""
    return [ln for ln in text.splitlines() if any(p.search(ln) for p in PRIVATE_PATTERNS)]


def policy_section(text):
    i = text.find('## Import policy')
    return text[i:] if i >= 0 else ''


def check(page_text, doc_for_policy=None):
    """Problems of a committed page: header missing, private content, or an import policy that no longer matches the code."""
    problems = []
    if not page_text.startswith(HEADER):
        problems.append('generated header missing')
    for ln in private_hits(page_text):
        problems.append('private content: ' + ln[:80])
    want = '\n'.join(x.rstrip() for x in policy_lines()) + '\n'
    if policy_section(page_text) != want:
        problems.append('import policy section is stale: run tools/cell_progress.py render-md')
    return problems
