#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Contents lists for the long public Markdown documents.

Usage:
  doc_toc.py write [FILE...]   add or refresh the contents list of every long document
  doc_toc.py check [FILE...]   exit 1 if a long document lacks an up-to-date list, or a
                               same-repository #anchor link resolves to no heading
  doc_toc.py list  [FILE...]   show which documents get a list and why

Without FILE arguments the documents are the Markdown files of the public file
list (tools/release-files.json).

Rule: a document gets a contents list when it has at least 150 lines and at least
3 entries to list. Entries are the second-level headings (and first-level headings
after the title); documents of 300 lines or more also list their third-level
headings, nested one level. Deeper headings are never listed. The list is a
"## Contents" section between the marker comments below, placed after the title
and its first intro paragraph (right after the title when there is no intro, or
when the intro ends with a colon and so leads into the block after it; a generated
block directly under the title, such as a bug page's fact table, counts as part of
the title), so a rerun replaces it. A document that no longer qualifies loses its
list on the next write.

Not edited: the root README.md (kept as is), licence texts, generated pages
(docs/BUGS.md: tools/bug_register.py renders it and its only section is the
register table; docs/AMIWIND_CONSOLE_COMMANDS.md: rendered whole by
tools/console_commands_doc.py) and frozen history (docs/journals/, released
docs/RELEASE-v*.md notes, docs/PATCH-*, docs/BUGS-v0.0.29-RC1.md,
docs/RC2_ISSUE_CHECKPOINT.md).

Links use GitHub's heading anchors: lower case, punctuation removed, each space a
hyphen, repeated anchors suffixed -1, -2 in document order.

check also follows every Markdown link with a #fragment (outside code) from the
public documents, frozen history excepted, to a Markdown file in the repository,
and fails when no heading or <a id/name> anchor there has that name
(DOCS-DEAD-ANCHORS-32).
"""
import html
import json
import re
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RELEASE_FILES = ROOT / 'tools' / 'release-files.json'
START = '<!-- contents start -->'
END = '<!-- contents end -->'
TITLE = 'Contents'
GENERATED_BEGIN = '<!-- BEGIN GENERATED '
GENERATED_END = '<!-- END GENERATED '
MIN_LINES = 150
NESTED_LINES = 300
MIN_ENTRIES = 3

EXCLUDED = {'README.md': 'the project front page stays as it is'}
GENERATED = {
    'docs/BUGS.md': 'generated by tools/bug_register.py; its one section is the register table',
    'docs/AMIWIND_CONSOLE_COMMANDS.md': 'generated whole by tools/console_commands_doc.py',
    'docs/bugs/CHIM_TRACKER.md': 'generated whole by tools/bug_register.py with the register',
    'docs/chim/FEATURES.md': 'generated whole by tools/chim_features.py from docs/chim/features.json',
    'docs/chim/CELL_TRACKER.md': 'generated whole by tools/cell_progress.py render-md from the tracker data',
}
FROZEN = {'docs/BUGS-v0.0.29-RC1.md', 'docs/RC2_ISSUE_CHECKPOINT.md'}
FROZEN_PREFIXES = ('docs/journals/', 'docs/RELEASE-v', 'docs/PATCH-')
LICENCE = re.compile(r'^(LICEN[CS]E|COPYING|NOTICE)', re.I)

HEADING = re.compile(r'^ {0,3}(#{1,6})(?:[ \t]+(.*?))?[ \t]*$')
FENCE = re.compile(r'^ {0,3}(`{3,}|~{3,})')
CODE_SPAN = re.compile(r'(?<!`)(`+)(?!`)(.+?)(?<!`)\1(?!`)')
IMAGE = re.compile(r'!\[([^\]]*)\]\([^)]*\)')
LINK = re.compile(r'\[([^\]]*)\](?:\([^)]*\)|\[[^\]]*\])')
AUTOLINK = re.compile(r'<((?:https?|mailto):[^>\s]+)>')
TAG = re.compile(r'</?[A-Za-z][^<>]*>')
ESCAPE = re.compile(r'\\([!-/:-@\[-`{-~])')


def excluded(rel):
    """Why a public file is never edited, or None."""
    rel = rel.replace('\\', '/')
    if rel in EXCLUDED:
        return EXCLUDED[rel]
    if rel in GENERATED:
        return GENERATED[rel]
    if rel in FROZEN or rel.startswith(FROZEN_PREFIXES):
        return 'frozen history'
    if LICENCE.match(rel.rsplit('/', 1)[-1]):
        return 'licence text'
    return None


def prose(lines):
    """(line index, line) of every line outside code fences and multi-line comments."""
    fence = None
    comment = False
    for i, line in enumerate(lines):
        if fence:
            m = FENCE.match(line)
            if m and m.group(1)[0] == fence[0] and len(m.group(1)) >= len(fence) and not line[m.end():].strip():
                fence = None
            continue
        if comment:
            if '-->' in line:
                comment = False
            continue
        m = FENCE.match(line)
        if m and not (m.group(1)[0] == '`' and '`' in line[m.end():]):
            fence = m.group(1)
            continue
        stripped = line.lstrip(' ')
        if len(line) - len(stripped) <= 3 and stripped.startswith('<!--') and '-->' not in stripped:
            comment = True
            continue
        yield i, line


def headings(lines):
    """(line index, level, raw text) of every ATX heading outside code fences and comments."""
    out = []
    for i, line in prose(lines):
        m = HEADING.match(line)
        if m:
            text = m.group(2) or ''
            text = re.sub(r'(?:^|[ \t]+)#+$', '', text)
            out.append((i, len(m.group(1)), text.strip()))
    return out


def _split_code(text):
    """[(is_code, segment)] with code span content unwrapped."""
    out, pos = [], 0
    for m in CODE_SPAN.finditer(text):
        out.append((False, text[pos:m.start()]))
        body = m.group(2)
        if len(body) > 1 and body[0] == ' ' and body[-1] == ' ' and body.strip():
            body = body[1:-1]
        out.append((True, body))
        pos = m.end()
    out.append((False, text[pos:]))
    return out


def _strip_underscores(seg):
    """Drop paired _ emphasis delimiters; intraword and unpaired underscores stay."""
    runs = list(re.finditer(r'_+', seg))
    drop = set()
    stack = []
    for n, m in enumerate(runs):
        before = seg[m.start() - 1] if m.start() else ' '
        after = seg[m.end()] if m.end() < len(seg) else ' '
        loose = lambda c: c.isspace() or (not c.isalnum())
        can_open = not after.isspace() and loose(before)
        can_close = not before.isspace() and loose(after)
        if can_close and stack:
            drop.update((stack.pop(), n))
        elif can_open:
            stack.append(n)
    out, pos = [], 0
    for n, m in enumerate(runs):
        if n in drop:
            out.append(seg[pos:m.start()])
            pos = m.end()
    out.append(seg[pos:])
    return ''.join(out)


def plain(text):
    """The rendered text of a heading's inline Markdown (what GitHub slugs)."""
    parts = []
    for code, seg in _split_code(text):
        if code:
            parts.append(seg)
            continue
        seg = IMAGE.sub('', seg)
        seg = LINK.sub(r'\1', seg)
        seg = AUTOLINK.sub(r'\1', seg)
        seg = TAG.sub('', seg)
        escaped = []
        seg = ESCAPE.sub(lambda m: escaped.append(m.group(1)) or '\x00', seg)
        seg = seg.replace('*', '').replace('~~', '')
        seg = _strip_underscores(seg)
        seg = re.sub('\x00', lambda m: escaped.pop(0), seg)
        parts.append(html.unescape(seg))
    return ''.join(parts).strip()


def _kept(c):
    if c in ' -_':
        return True
    cat = unicodedata.category(c)
    return cat[0] in 'LM' or cat in ('Nd', 'Nl', 'Pc')


def slug(text):
    """GitHub's anchor for one heading text, before duplicate numbering."""
    return ''.join(c for c in plain(text).lower() if _kept(c)).replace(' ', '-')


class Slugger:
    """Duplicate numbering as GitHub does it: foo, foo-1, foo-2 ..."""

    def __init__(self):
        self.seen = {}

    def __call__(self, text):
        base = result = slug(text)
        while result in self.seen:
            self.seen[base] += 1
            result = '%s-%d' % (base, self.seen[base])
        self.seen[result] = 0
        return result


def label(text):
    """Link text for a heading: inline Markdown kept, links unwrapped, brackets escaped."""
    parts = []
    for code, seg in _split_code(text):
        if code:
            ticks = '``' if '`' in seg else '`'
            pad = ' ' if seg.startswith('`') or seg.endswith('`') else ''
            parts.append(ticks + pad + seg + pad + ticks)
            continue
        seg = IMAGE.sub('', seg)
        seg = LINK.sub(r'\1', seg)
        seg = AUTOLINK.sub(r'\1', seg)
        seg = TAG.sub('', seg)
        seg = re.sub(r'(?<!\\)([\[\]])', r'\\\1', seg)
        parts.append(seg)
    return ''.join(parts).strip()


INLINE_TARGET = re.compile(r'(?<!!)\[(?:[^\]\\]|\\.)*\]\(\s*<?([^)\s>]+)>?(?:\s+"[^"]*")?\s*\)')
REFERENCE_TARGET = re.compile(r'^ {0,3}\[[^\]]+\]:\s*<?([^\s>]+)>?')
HTML_ANCHOR = re.compile(r'<a\s+(?:id|name)="([^"]+)"')
SCHEME = re.compile(r'^[A-Za-z][A-Za-z0-9+.-]*:')


def anchors(text):
    """Every fragment a document answers to: heading anchors and explicit <a id/name> anchors."""
    lines = text.split('\n')
    slugger = Slugger()
    found = {slugger(raw) for _, _, raw in headings(lines)}
    return found | {m.group(1) for _, line in prose(lines) for m in HTML_ANCHOR.finditer(line)}


def anchor_links(text):
    """(line number, target) of every Markdown link with a #fragment, outside code.

    Link text may wrap over lines, so links are matched in the whole text with code
    fences, comments and code spans blanked out (line numbers are kept).
    """
    lines = text.split('\n')
    masked = [''] * len(lines)
    found = []
    for i, line in prose(lines):
        masked[i] = CODE_SPAN.sub(lambda m: ' ' * len(m.group(0)), line)
        m = REFERENCE_TARGET.match(masked[i])
        if m:
            found.append((i + 1, m.group(1)))
    joined = '\n'.join(masked)
    found += [(joined.count('\n', 0, m.start(1)) + 1, m.group(1)) for m in INLINE_TARGET.finditer(joined)]
    return sorted((n, t) for n, t in found if '#' in t and not SCHEME.match(t))


def dead_anchors(sources, root=ROOT, texts=None):
    """'file:line: target' for every same-repository #anchor link that resolves to no heading.

    Links to other files are checked when the target is a Markdown file that exists;
    a missing file is not this check's business. Frozen history is not a source:
    it keeps its links as they were written.
    """
    import posixpath
    from urllib.parse import unquote
    texts = {} if texts is None else texts  # repository path -> text, read once
    cache = {}  # repository path -> anchors, or None when it is not a Markdown file there

    def read(rel):
        if rel not in texts:
            path = root / rel
            texts[rel] = path.read_bytes().decode('utf-8') if rel.endswith('.md') and path.is_file() else None
        return texts[rel]

    def known(dest):
        if dest not in cache:
            text = read(dest)
            cache[dest] = None if text is None else anchors(text)
        return cache[dest]

    dead = []
    for rel in sources:
        rel = rel.replace('\\', '/')
        if excluded(rel) == 'frozen history' or known(rel) is None:
            continue
        for line, target in anchor_links(read(rel)):
            file_part, _, fragment = target.partition('#')
            dest = posixpath.normpath(posixpath.join(posixpath.dirname(rel), unquote(file_part))) if file_part else rel
            found = known(dest)
            if found is not None and unquote(fragment) not in found:
                dead.append('%s:%d: %s' % (rel, line, target))
    return dead


def strip_block(text):
    """The document without its contents block (unchanged if it has none)."""
    lines = text.split('\n')
    starts = [i for i, l in enumerate(lines) if l.strip() == START]
    ends = [i for i, l in enumerate(lines) if l.strip() == END]
    if not starts and not ends:
        return text
    if len(starts) != 1 or len(ends) != 1 or ends[0] < starts[0]:
        raise ValueError('needs exactly one %s ... %s block' % (START, END))
    before = lines[:starts[0]]
    after = lines[ends[0] + 1:]
    while before and not before[-1].strip():
        before.pop()
    while after and after[0].strip() == '' and len(after) > 1:
        after.pop(0)
    return '\n'.join(before + [''] + after if before else after)


def _title(lines, found):
    first = next((i for i, l in enumerate(lines) if l.strip()), None)
    for i, level, _ in found:
        if i == first and level == 1:
            return i
    return None


def _insert_at(lines, title):
    if title is None:
        return 0
    j = title + 1
    while j < len(lines) and not lines[j].strip():
        j += 1
    # A generated block right under the title (a bug page's fact table, written by
    # tools/bug_register.py render) stays with the title: the list goes after it, so the
    # two generators never move each other's blocks.
    while j < len(lines) and lines[j].startswith(GENERATED_BEGIN):
        end = next((k for k in range(j + 1, len(lines)) if lines[k].startswith(GENERATED_END)), None)
        if end is None:
            break
        title = end
        j = end + 1
        while j < len(lines) and not lines[j].strip():
            j += 1
    if j >= len(lines):
        return title + 1
    first = lines[j].lstrip(' ')
    intro = not (HEADING.match(lines[j]) or FENCE.match(lines[j]) or first.startswith(('|', '<!--', '- ', '* ', '+ '))
                 or re.match(r'\d+[.)] ', first) or lines[j].startswith('    '))
    if not intro:
        return title + 1
    while j < len(lines) and lines[j].strip() and not HEADING.match(lines[j]) and not FENCE.match(lines[j]):
        j += 1
    if lines[j - 1].rstrip().endswith(':'):
        return title + 1  # the intro leads into what follows it; keep them together
    return j


def plan(text):
    """(qualifies, entries, line count) for a document without its block.

    entries are (depth, label, anchor), depth 0 or 1.
    """
    lines = text.split('\n')
    found = headings(lines)
    title = _title(lines, found)
    count = len(text.splitlines())
    nested = count >= NESTED_LINES
    slugger = Slugger()
    entries = []
    contents_done = False
    insert = _insert_at(lines, title)
    for i, level, raw in found:
        if not contents_done and i >= insert:
            slugger(TITLE)
            contents_done = True
        anchor = slugger(raw)
        if i == title:
            continue
        if level <= 2:
            entries.append((0, label(raw), anchor))
        elif level == 3 and nested:
            entries.append((1 if entries else 0, label(raw), anchor))
    return count >= MIN_LINES and len(entries) >= MIN_ENTRIES, entries, count


def block(entries):
    out = [START, '## ' + TITLE, '']
    out += ['%s- [%s](#%s)' % ('  ' * depth, text, anchor) for depth, text, anchor in entries]
    return out + ['', END]


def render(text):
    """The document with its contents list added, refreshed or removed."""
    base = strip_block(text)
    ok, entries, _ = plan(base)
    if not ok:
        return base
    lines = base.split('\n')
    at = _insert_at(lines, _title(lines, headings(lines)))
    before, after = lines[:at], lines[at:]
    while before and not before[-1].strip():
        before.pop()
    while after and after[0].strip() == '' and len(after) > 1:
        after.pop(0)
    new = (before + [''] if before else []) + block(entries) + [''] + after
    return '\n'.join(new)


def public_docs():
    files = json.loads(RELEASE_FILES.read_text(encoding='utf-8'))
    return sorted(f for f in files if f.endswith('.md'))


def _targets(args):
    return [a.replace('\\', '/') for a in args] if args else public_docs()


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    if not argv or argv[0] not in ('write', 'check', 'list'):
        print(__doc__, file=sys.stderr)
        return 2
    mode, files = argv[0], _targets(argv[1:])
    stale, changed, texts = [], [], {}
    for rel in files:
        path = ROOT / rel
        if not path.is_file():
            continue
        text = texts[rel] = path.read_bytes().decode('utf-8')
        why = excluded(rel)
        if why:
            if START in text or END in text:
                stale.append('%s: excluded (%s) but has a contents block' % (rel, why))
            if mode == 'list':
                print('skip  %s (%s)' % (rel, why))
            continue
        try:
            new = render(text)
        except ValueError as exc:
            stale.append('%s: %s' % (rel, exc))
            continue
        if mode == 'list':
            ok, entries, count = plan(strip_block(text))
            print('%s  %s (%d lines, %d entries)' % ('list' if ok else 'none', rel, count, len(entries)))
            continue
        if new != text:
            if mode == 'write':
                path.write_bytes(new.encode('utf-8'))
                changed.append(rel)
            else:
                stale.append('%s: contents list missing or out of date' % rel)
    for line in stale:
        print(line, file=sys.stderr)
    if mode == 'check':
        dead = dead_anchors(files, texts=texts)
        for line in dead:
            print('%s: no heading or anchor with this name' % line, file=sys.stderr)
        if stale:
            print('run tools/doc_toc.py write', file=sys.stderr)
        if dead:
            print('repoint the dead #anchor links to current headings', file=sys.stderr)
        if stale or dead:
            return 1
        print('contents lists and #anchor links ok: %d documents checked' % len(files))
        return 0
    if mode == 'write':
        for rel in changed:
            print('wrote', rel)
        print('%d documents updated' % len(changed))
    return 1 if stale else 0


if __name__ == '__main__':
    sys.exit(main())
