#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Compare a built payload with what the last release ships, feature by feature.

Release coverage (BUILD-HANDS-NOT-BUILT-32, BUILD-HARVEST-NOT-BUILT-32): a
release ships classes of files (world maps, per-race hands, harvest data,
...). config/release-features.json names every feature, the path patterns of
its files and the builder steps that make them; config/release-payload-classes.json
records the path classes of the last release (generated by `classes`, no game
data: numbers become '#', hashes '<h>'). `check` lists, for a real payload,
the features it lacks, the release classes it lacks and the files no feature
explains. The from-scratch release gate runs it on the finished image.

    payload_coverage.py check PAYLOAD [PAYLOAD ...] [--json] [--allow-known-gaps]
    payload_coverage.py classes PAYLOAD --release vX.Y.Z [--recorded-from TEXT] > config/release-payload-classes.json

A release that adds a file class (a new feature, or a town that becomes
shipped in config/towns.json) records the classes of its newest complete
payload as the new baseline in the same change, with --recorded-from naming
that payload, and records them again from the published release payload.

PAYLOAD is a payload manifest ({"files": [{"path": ...}]}, as written by the
HDF payload reader), a JSON list of paths, or a staged directory (for example
an image step's boot/ folder; paths are relative to it).
"""
import argparse
from collections import Counter
import fnmatch
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
FEATURES = ROOT / 'config/release-features.json'
CLASSES = ROOT / 'config/release-payload-classes.json'


def path_class(path):
    """A path with its varying parts generalised: hex runs (10+) -> <h>, digits -> #."""
    head, _, name = path.rpartition('/')
    stem, dot, ext = name.partition('.')
    stem = re.sub(r'[0-9a-f]{10,}', '<h>', stem)
    stem = re.sub(r'[0-9]+', '#', stem)
    return (head + '/' if head else '') + stem + dot + ext


def matches(pattern, path):
    """Glob per path segment: '*' and '?' never cross '/'."""
    parts, names = pattern.split('/'), path.split('/')
    return len(parts) == len(names) and all(fnmatch.fnmatchcase(n, p) for p, n in zip(parts, names))


def town_patterns(town_id, root=None):
    """Payload patterns of one imported town, from its town block (config/towns.json row and config).

    The town map, its region maps (<prefix>NNN), its region table and door
    table, and its interior maps (<prefix>iNNN) once the town lists rooms.
    """
    from town_config import load_settings, town_field
    settings = load_settings(town_id, root)
    name, prefix = town_field(settings, 'map'), town_field(settings, 'map_prefix')
    return ['id1/maps/' + name + '.bsp', 'id1/maps/' + prefix + '[0-9][0-9][0-9].bsp',
            'id1/' + town_field(settings, 'region_file'), 'id1/' + town_field(settings, 'door_file'),
            'id1/maps/' + prefix + 'i[0-9][0-9][0-9].bsp']


def expand_town_features(config, root=None):
    """Fill features that name "towns": "shipped" from the town table (BUILD-EXTRA-TOWN-OPTIN-32).

    Every town config/towns.json marks shipped_since adds its patterns and
    its builder step town-<id>, so a newly shipped town needs no edit here.
    """
    from town_config import shipped_extra_towns
    for feature in config['features']:
        selection = feature.get('towns')
        if selection is None:
            continue
        if selection != 'shipped':
            raise ValueError('Unknown town selection in release feature ' + feature['id'])
        towns = shipped_extra_towns(root)
        feature['patterns'] = [*feature.get('patterns', []), *(p for town in towns for p in town_patterns(town, root))]
        feature['steps'] = [*('town-' + town for town in towns), *feature.get('steps', [])]
    return config


def load_features(path=FEATURES, root=None):
    config = json.loads(Path(path).read_text(encoding='utf-8'))
    if config.get('format') != 'AmiWind release features 1':
        raise ValueError('Unknown release feature list format')
    expand_town_features(config, root)
    ids = [feature['id'] for feature in config['features']]
    if len(ids) != len(set(ids)):
        raise ValueError('Duplicate release feature id')
    return config


def load_classes(path=CLASSES):
    record = json.loads(Path(path).read_text(encoding='utf-8'))
    if record.get('format') != 'AmiWind release payload classes 1':
        raise ValueError('Unknown release payload class format')
    return record


def load_payload(source):
    """Payload paths from a manifest, a JSON path list or a staged directory."""
    source = Path(source)
    if source.is_dir():
        return sorted(p.relative_to(source).as_posix() for p in source.rglob('*') if p.is_file())
    data = json.loads(source.read_text(encoding='utf-8'))
    rows = data['files'] if isinstance(data, dict) else data
    return sorted(row['path'] if isinstance(row, dict) else row for row in rows)


def feature_of(path, features):
    """The ids of the features whose patterns match a path (exactly one is expected)."""
    return [feature['id'] for feature in features if any(matches(p, path) for p in feature['patterns'])]


def compare(paths, config, baseline):
    """Feature counts, missing features/classes, unexplained and new files."""
    features = config['features']
    gaps = config.get('builder_gaps', {})
    counts = Counter()
    unexplained, ambiguous = [], []
    for path in paths:
        owners = feature_of(path, features)
        if not owners:
            unexplained.append(path)
        elif len(owners) > 1:
            ambiguous.append((path, owners))
        for owner in owners:
            counts[owner] += 1
    classes = Counter(path_class(path) for path in paths)
    expected = baseline['classes']
    missing_features = [feature['id'] for feature in features if not counts[feature['id']]]
    return {
        'release': baseline['release'],
        'files': len(paths),
        'features': {feature['id']: counts[feature['id']] for feature in features},
        'missing_features': [f for f in missing_features if f not in gaps],
        'known_gaps': {f: gaps[f] for f in missing_features if f in gaps},
        'missing_classes': sorted(c for c in expected if c not in classes),
        'new_classes': sorted(c for c in classes if c not in expected),
        'unexplained_files': unexplained,
        'ambiguous_files': ambiguous,
    }


def failed(report, allow_known_gaps=False):
    return bool(report['missing_features'] or report['unexplained_files'] or report['ambiguous_files']
                or (report['known_gaps'] and not allow_known_gaps)
                or (report['missing_classes'] and not allow_known_gaps))


def text(report):
    lines = [f"Payload: {report['files']} files, compared with {report['release']}"]
    width = max(map(len, report['features']))
    for feature, count in report['features'].items():
        note = (' MISSING (known builder gap: ' + report['known_gaps'][feature] + ')' if feature in report['known_gaps']
                else ' MISSING' if not count else '')
        lines.append(f'  {feature:<{width}} {count:>6}{note}')
    for key, title in (('missing_features', 'Missing features'), ('missing_classes', 'Release classes not in this payload'),
                       ('new_classes', 'Classes not in the release'), ('unexplained_files', 'Files no feature explains')):
        if report[key]:
            lines.append(f'{title} ({len(report[key])}):')
            lines += ['  ' + item for item in report[key][:50]]
            if len(report[key]) > 50:
                lines.append(f'  ... {len(report[key]) - 50} more')
    for path, owners in report['ambiguous_files'][:50]:
        lines.append(f'Ambiguous: {path} -> {", ".join(owners)}')
    return '\n'.join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest='command', required=True)
    check = sub.add_parser('check', help='Compare payloads with the release features')
    check.add_argument('payload', nargs='+', type=Path)
    check.add_argument('--features', type=Path, default=FEATURES)
    check.add_argument('--classes', type=Path, default=CLASSES)
    check.add_argument('--json', action='store_true', help='Print the report as JSON')
    check.add_argument('--allow-known-gaps', action='store_true',
                       help='Development builds only: do not fail on recorded builder gaps')
    classes = sub.add_parser('classes', help='Record the path classes of a release payload')
    classes.add_argument('payload', nargs='+', type=Path)
    classes.add_argument('--release', required=True)
    classes.add_argument('--recorded-from', metavar='TEXT',
                         help='Which payload the classes come from when it is not the published release '
                              '(for example the newest playtest of a release in preparation)')
    args = parser.parse_args(argv)
    paths = sorted({path for source in args.payload for path in load_payload(source)})
    if args.command == 'classes':
        counts = Counter(path_class(path) for path in paths)
        record = {'format': 'AmiWind release payload classes 1', 'release': args.release,
                  **({'recorded_from': args.recorded_from} if args.recorded_from else {}),
                  'files': len(paths), 'classes': dict(sorted(counts.items()))}
        sys.stdout.write(json.dumps(record, indent=1) + '\n')
        return 0
    report = compare(paths, load_features(args.features), load_classes(args.classes))
    print(json.dumps(report, indent=1) if args.json else text(report))
    return 1 if failed(report, args.allow_known_gaps) else 0


if __name__ == '__main__':
    sys.exit(main())
