# SPDX-License-Identifier: GPL-3.0-only
"""Self-contained private planning atlas and north-up static overview."""
import base64
import json
import math
from pathlib import Path
from PIL import Image, ImageDraw


def render(report, out):
    out = Path(out)
    source = Image.open(out/'terrain.png').convert('RGBA')
    background = Image.new('RGBA', source.size, (19, 40, 53, 255)); background.alpha_composite(source)
    draw = ImageDraw.Draw(background)
    x0,y0,x1,y1 = report['terrain_bounds']
    def xy(p):return ((p[0]/8192-x0)*32, (y1-p[1]/8192)*32)
    for area in report['areas']:
        for r in area['regions']:
            a,b=xy(r['core'][0]),xy(r['core'][1])
            draw.rectangle((a[0],b[1],b[0],a[1]),outline='#ffda74',width=1)
        point=xy(area['centre']);draw.text((point[0]+5,point[1]+5),area['name'],fill='white',stroke_width=2,stroke_fill='black')
    background.convert('RGB').save(out/'overview.png')
    payload = json.dumps(report,separators=(',',':')).replace('<','\\u003c')
    picture = base64.b64encode((out/'terrain.png').read_bytes()).decode()
    html=HTML.replace('__DATA__',payload).replace('__IMAGE__',picture)
    (out/'Vvardenfell-atlas.html').write_text(html)


HTML = r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>AmiWind · Vvardenfell survey</title><style>
*{box-sizing:border-box}body{margin:0;background:#101c24;color:#e6e7e3;font:15px system-ui,sans-serif}header{padding:16px 22px;border-bottom:1px solid #32434d;display:flex;gap:20px;align-items:center;flex-wrap:wrap}h1{font:600 22px Georgia,serif;margin:0}small{color:#aebfc7}main{display:grid;grid-template-columns:minmax(0,1fr) 320px;height:calc(100vh - 82px);min-height:480px}#map{width:100%;height:100%;touch-action:none;display:block;background:#132835;cursor:grab}aside{padding:20px;overflow:auto;border-left:1px solid #32434d}button,select,input{background:#1e303c;color:#f3efe3;border:1px solid #506471;border-radius:4px;padding:7px}button{cursor:pointer}button:hover{background:#334e5d}label{display:block;margin:12px 0}input[type=number]{width:76px}h2{font:600 19px Georgia,serif;color:#f0d699}pre{white-space:pre-wrap;font:13px/1.55 ui-monospace,monospace}p{line-height:1.5}#legend{color:#aebfc7;font-size:13px}#status{margin-left:auto}a{color:#efce88} .row{display:flex;gap:5px;flex-wrap:wrap}@media(max-width:800px){main{grid-template-columns:1fr;height:auto}#map{height:62vh}aside{border-left:0}header{padding:12px}#status{margin:0}}
</style><header><div><h1>AmiWind · Vvardenfell</h1><small>Base-master terrain, geometry density and existing regions</small></div><select id="layer"><option value="terrain">Terrain colours</option><option value="density">Triangle density</option><option value="candidates">Sub-cell candidates</option></select><button id="reset">Fit island</button><span id="status"></span></header>
<main><canvas id="map"></canvas><aside><h2>World survey</h2><p id="intro"></p><label><input id="grid" type="checkbox" checked> Original cell boundaries</label><label><input id="regions" type="checkbox" checked> Existing Balmora / Seyda Neen cores</label><label><input id="overlap" type="checkbox"> Existing loading overlap</label><p id="legend">Drag to pan. Wheel to zoom. Click a cell for measurements. North is up.</p><h2 id="celltitle">Choose a cell</h2><pre id="details"></pre><h2>Locate runtime coordinates</h2><select id="area"></select><div class="row"><label>X <input id="lx" type="number" value="0"></label><label>Y <input id="ly" type="number" value="0"></label><label>Z <input id="lz" type="number" value="0"></label></div><button id="locate">Place marker</button><p id="location"></p><h2>Reading the results</h2><p>Density assigns each source triangle once by its centre. Loading estimates count complete intersecting objects, including overlap.</p><p>Subdivision colours are screening candidates, not certified Amiga budgets. Terrain, actors, textures, collision, heap use and transition timings still need converted/native checks.</p><p>Ocean fills the view outside the terrain preview. This is a planning atlas, not a playable world or proof of continuous ocean travel.</p></aside></main>
<script>
'use strict';const data=__DATA__;const cv=document.getElementById('map'),ctx=cv.getContext('2d');const $=id=>document.getElementById(id);const img=new Image();img.src='data:image/png;base64,__IMAGE__';const [x0,y0,x1,y1]=data.terrain_bounds;let scale=1,ox=0,oy=0,selected=null,marker=null,drag=null,moved=false;const byCell=new Map(data.cells.map(c=>[c.cell.join(','),c]));const maxDensity=Math.max(1,...data.cells.map(c=>Math.max(...c.subtiles)));const colors={1:'#48b7a2',2:'#e2c45a',4:'#ed9253',8:'#d86869',null:'#b085cf'};
$('intro').textContent=`${data.summary.terrain_cells.toLocaleString()} terrain cells; ${data.summary.measured_placements.toLocaleString()} placed objects measured. ${data.summary.unresolved_placements} unresolved placements.`;for(const a of data.areas){let o=document.createElement('option');o.textContent=a.name;$('area').append(o)}
function world(px,py){return [(px-ox)/scale,(oy-py)/scale]};function pixel(x,y){return [ox+x*scale,oy-y*scale]};function rect(a,b,fill,stroke){let p=pixel(a[0],b[1]),w=(b[0]-a[0])*scale,h=(b[1]-a[1])*scale;if(fill){ctx.fillStyle=fill;ctx.fillRect(p[0],p[1],w,h)}if(stroke){ctx.strokeStyle=stroke;ctx.strokeRect(p[0],p[1],w,h)}}
function fit(){scale=Math.min(cv.clientWidth/((x1-x0+4)*8192),cv.clientHeight/((y1-y0+4)*8192));ox=cv.clientWidth/2-(x0+x1)*4096*scale;oy=cv.clientHeight/2+(y0+y1)*4096*scale;draw()}
function resize(){const d=devicePixelRatio||1;cv.width=cv.clientWidth*d;cv.height=cv.clientHeight*d;ctx.setTransform(d,0,0,d,0,0);draw()}
function draw(){const w=cv.clientWidth,h=cv.clientHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#132835';ctx.fillRect(0,0,w,h);let p=pixel(x0*8192,y1*8192);ctx.imageSmoothingEnabled=false;if(img.complete)ctx.drawImage(img,p[0],p[1],(x1-x0)*8192*scale,(y1-y0)*8192*scale);let mode=$('layer').value;
for(const c of data.cells){let a=c.cell.map(v=>v*8192),b=a.map(v=>v+8192),p=pixel(a[0],b[1]),side=8192*scale;if(p[0]>w||p[0]+side<0||p[1]>h||p[1]+side<0)continue;if(mode==='density'){for(let y=0;y<4;y++)for(let x=0;x<4;x++){let n=c.subtiles[y*4+x];if(n){let f=Math.log1p(n)/Math.log1p(maxDensity);rect([a[0]+x*2048,a[1]+y*2048],[a[0]+(x+1)*2048,a[1]+(y+1)*2048],`hsla(${230-230*f},85%,55%,.83)`)}}}else if(mode==='candidates'){ctx.globalAlpha=.68;rect(a,b,c.unresolved_placements?'#ed42c1':colors[c.screen.candidate]);ctx.globalAlpha=1}if($('grid').checked&&side>5)rect(a,b,null,'#ffffff30')}
for(const a of data.areas){for(const r of a.regions){if($('overlap').checked)rect(r.coverage[0],r.coverage[1],null,'#e6a54045');if($('regions').checked)rect(r.core[0],r.core[1],null,'#ffdb7c')}let p=pixel(...a.centre);ctx.font='bold 13px system-ui';ctx.lineWidth=3;ctx.strokeStyle='#10202b';ctx.strokeText(a.name,p[0]+6,p[1]-6);ctx.fillStyle='#fff1c3';ctx.fillText(a.name,p[0]+6,p[1]-6);ctx.lineWidth=1}
if(selected)rect(selected.cell.map(v=>v*8192),selected.cell.map(v=>(v+1)*8192),null,'white');if(marker){let p=pixel(marker[0],marker[1]);ctx.strokeStyle='white';ctx.beginPath();ctx.arc(...p,7,0,Math.PI*2);ctx.moveTo(p[0]-12,p[1]);ctx.lineTo(p[0]+12,p[1]);ctx.moveTo(p[0],p[1]-12);ctx.lineTo(p[0],p[1]+12);ctx.stroke()}
$('status').textContent=`${Math.round(8192*scale)} px / source cell`;$('legend').textContent=mode==='candidates'?'Green: 1 cell; yellow: 2×2; orange: 4×4; red: 8×8; purple: still exceeds; magenta: incomplete. Screening only.':mode==='density'?'Blue → red: logarithmic source triangle density. Counts include placed copies; actors excluded.':'Drag to pan. Wheel to zoom. Click a cell. North is up.'}
function inspect(c){selected=c;if(!c){$('celltitle').textContent='No source cell';$('details').textContent='Ocean or outside the supplied master coverage.';draw();return}$('celltitle').textContent=c.name||c.region||'Unnamed exterior';let s=c.screen;let lines=[`Cell: ${c.cell.join(', ')}`,`Terrain: ${c.has_terrain?'present':'absent'}`,`Height: ${c.min_height??'?'} … ${c.max_height??'?'}`,`Source triangles in cell: ${c.spatial_source_triangles.toLocaleString()}`,`Owned placed triangles: ${c.owned_source_triangles.toLocaleString()}`,`Unresolved placements: ${c.unresolved_placements}`,`Candidate: ${s.candidate?s.candidate+'×'+s.candidate:'requires further work'}`,`Status: ${s.status}`,'',...s.options.map(o=>`${o.divisions}×${o.divisions}: peak ${o.peak_source_triangles.toLocaleString()} tris / ${o.peak_references} refs`),'',`Actor records: ${(c.types.NPC_||0)+(c.types.CREA||0)}`,`Leveled creatures: ${c.types.LEVC||0}`];$('details').textContent=lines.join('\n');draw()}
cv.addEventListener('pointerdown',e=>{cv.setPointerCapture(e.pointerId);drag={x:e.offsetX,y:e.offsetY,ox,oy};moved=false});cv.addEventListener('pointermove',e=>{if(drag){let dx=e.offsetX-drag.x,dy=e.offsetY-drag.y;if(Math.hypot(dx,dy)>3)moved=true;ox=drag.ox+dx;oy=drag.oy+dy;draw()}});cv.addEventListener('pointerup',e=>{if(!moved){let p=world(e.offsetX,e.offsetY);inspect(byCell.get(p.map(v=>Math.floor(v/8192)).join(',')))}drag=null});cv.addEventListener('pointercancel',()=>drag=null);cv.addEventListener('wheel',e=>{e.preventDefault();let p=world(e.offsetX,e.offsetY);scale=Math.max(.0002,Math.min(.05,scale*Math.exp(-e.deltaY*.001)));ox=e.offsetX-p[0]*scale;oy=e.offsetY+p[1]*scale;draw()},{passive:false});for(const id of ['grid','regions','overlap','layer'])$(id).addEventListener('change',draw);$('reset').onclick=fit;$('locate').onclick=()=>{let a=data.areas[$('area').selectedIndex],v=['lx','ly','lz'].map(id=>Number($(id).value));if(!v.every(Number.isFinite))return;marker=v.map((n,i)=>n/a.scale+(i<2?a.centre[i]:0));$('location').textContent=`World XYZ: ${marker.map(n=>n.toFixed(1)).join(', ')}; cell ${marker.slice(0,2).map(n=>Math.floor(n/8192)).join(', ')}. Exterior transforms only.`;ox=cv.clientWidth/2-marker[0]*scale;oy=cv.clientHeight/2+marker[1]*scale;draw()};new ResizeObserver(resize).observe(cv);img.onload=()=>{resize();fit()};
</script></html>'''
