#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generate the engine's town table (engine/aga/src/aw_town_table.h).

The runtime knows towns only through this table: map name, region prefix and
directory, region cap, draw distance, world-directory slot or handoff frame,
behaviour flags and travel. It is generated from config/towns.json and the
town configs, checked in so native tests compile without a generator step,
and verified by build_aga.py engine and tests/test_town_import.py.

  python3 tools/town_table.py --write   # after changing a town config
  python3 tools/town_table.py --check   # exit 1 when the header is stale
"""
import argparse
from pathlib import Path
import sys

from town_config import FIXED_TOWNS, runtime_towns, town_interiors

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / 'engine/aga/src/aw_town_table.h'
FLAG_MACROS = {'seyda_scenes': 'AW_TOWN_SEYDA_SCENES', 'legacy_payload': 'AW_TOWN_LEGACY_PAYLOAD',
               'own_doors': 'AW_TOWN_OWN_DOORS', 'scenery_catalogue': 'AW_TOWN_SCENERY',
               'teleport_arrival': 'AW_TOWN_TELEPORT', 'ground_place': 'AW_TOWN_GROUND_PLACE'}


def c_string(value):
    if any(c in value for c in '"\\\r\n') or not value.isascii():
        raise ValueError('Town table strings must be plain ASCII')
    return '"' + value + '"'


def c_float(value):
    text = repr(float(value))
    return text[:-2] if text.endswith('.0') else text


def c_list(name, values, per_line):
    """#define NAME {v,...} on one line, or continued lines of per_line values."""
    if len(values) <= per_line:
        return ['#define ' + name + ' {' + ','.join(values) + '}']
    lines = ['#define ' + name + ' {\\']
    for i in range(0, len(values), per_line):
        last = i + per_line >= len(values)
        lines.append('    ' + ','.join(values[i:i + per_line]) + ('' if last else ',') + '\\')
    return lines + ['}']


def render_header(root=None):
    rows = runtime_towns(root)
    extra = rows[len(FIXED_TOWNS):]
    rooms = town_interiors(root)
    ids = [r['id'] for r in rows]
    lines = [
        '/* SPDX-License-Identifier: GPL-2.0-or-later',
        ' * Generated by tools/town_table.py from config/towns.json and the town',
        ' * configs. Do not edit: change the configs and run tools/town_table.py --write.',
        ' * Row order is the stable save order; extra towns take save IDs from',
        ' * AW_TOWN_MAP_BASE, town interiors (towns in row order, then each',
        ' * list order of its town) from AW_TOWN_INTERIOR_BASE (aw_maps.h). */',
        '#ifndef AW_TOWN_TABLE_H',
        '#define AW_TOWN_TABLE_H',
        f'#define AW_TOWN_COUNT {len(rows)}',
        f'#define AW_TOWN_FIXED_COUNT {len(FIXED_TOWNS)}',
        f'#define AW_TOWN_EXTRA_COUNT {len(extra)}',
        '#define AW_TOWN_EXTRA_NAMES {' + ','.join(c_string(r['name']) for r in extra or [{'name': ''}]) + '}',
        '#define AW_TOWN_EXTRA_TITLES {' + ','.join(c_string(r['title']) for r in extra or [{'title': ''}]) + '}',
        f'#define AW_TOWN_INTERIOR_COUNT {len(rooms)}',
        *c_list('AW_TOWN_INTERIOR_NAMES', [c_string(r['map']) for r in rooms] or ['""'], 8),
        *c_list('AW_TOWN_INTERIOR_TITLES', [c_string(r['title']) for r in rooms] or ['""'], 1),
        '/* Town row (AW_Town index) whose door bank leads into each interior. */',
        *c_list('AW_TOWN_INTERIOR_TOWNS', [str(ids.index(r['town'])) for r in rooms] or ['0'], 32),
        '/* name,title,prefix,regions,travel_npc,travel_target,region_cap,draw_distance,',
        '   world_slot,flags,travel_return,handoff,origin[3],core[4] */',
        '#define AW_TOWN_ROWS {\\',
    ]
    for i, r in enumerate(rows):
        flags = '|'.join(FLAG_MACROS[f] for f in r['flags']) or '0'
        values = [*map(c_string, (r['name'], r['title'], r['prefix'], r['regions'], r['travel_npc'], r['travel_target'])),
                  str(r['region_cap']), str(r['draw_distance']), str(r['world_slot']), flags,
                  str(int(r['travel_return'])), str(int(r['handoff'])),
                  '{' + ','.join(map(c_float, r['origin'])) + '}',
                  '{' + ','.join(map(c_float, [*r['core'][0], *r['core'][1]])) + '}']
        lines.append('    {' + ','.join(values) + '}' + (',' if i + 1 < len(rows) else '') + '\\')
    lines += ['}', '#endif', '']
    return '\n'.join(lines)


def check(root=None, header=None):
    """True when the checked-in header matches the configs."""
    header = Path(header or HEADER)
    return header.is_file() and header.read_text(encoding='ascii') == render_header(root)


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument('--write', action='store_true', help='Rewrite engine/aga/src/aw_town_table.h')
    mode.add_argument('--check', action='store_true', help='Fail when the header differs from the configs')
    a = p.parse_args(argv)
    if a.write:
        HEADER.write_text(render_header(), encoding='ascii', newline='\n')
        print('Wrote', HEADER.relative_to(ROOT).as_posix())
        return 0
    if check():
        print('Town table is current.')
        return 0
    print('engine/aga/src/aw_town_table.h is stale; run tools/town_table.py --write', file=sys.stderr)
    return 1


if __name__ == '__main__':
    raise SystemExit(main())
